import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import mongoose from 'mongoose';
import axios from 'axios';
import { env } from '../src/config/env.js';
import { redis, jobs } from '../src/shared/redis.js';
import { MonthlyUniverseModel, QualificationRunModel } from '../src/modules/qualification/models/qualification.model.js';
import { PaperPositionModel, PaperSessionModel, PaperSignalModel } from '../src/modules/paper-trading/models/paper.model.js';
import { StrategyModel } from '../src/modules/strategies/models/strategy.model.js';
import { BacktestRunModel } from '../src/modules/backtesting/models/backtest.model.js';
import { IndexCacheModel, IndexChartModel } from '../src/modules/market-indices/models/index-cache.model.js';
import { marketTime } from '../src/shared/market-calendar.js';
import { WatchlistModel } from '../src/modules/watchlists/models/watchlist.model.js';
import { saveDashboardPreferences } from '../src/modules/dashboard/services/preferences.service.js';
import { defaultDashboardPreferences } from '../src/modules/dashboard/validations/preferences.validation.js';

test('dashboard respects published results and missing marks; closed markets never start provider refreshes', { skip: process.env.RUN_DB_TESTS !== '1' }, async t => {
  const name = `quantforge_test_${randomUUID().replaceAll('-', '')}`, uri = new URL(env.MONGODB_URI); uri.pathname = `/${name}`;
  const adapter = axios.defaults.adapter;
  let requests = 0, refreshLocks = 0;
  axios.defaults.adapter = async () => { requests++; throw new Error('Unexpected external provider request'); };
  t.mock.method(redis, 'get', async () => null);
  t.mock.method(redis, 'exists', async () => 0);
  t.mock.method(redis, 'set', async () => { refreshLocks++; return null; });
  try {
    await mongoose.connect(uri.toString());
    const now = new Date().toISOString(), month = marketTime().date.slice(0, 7);
    await MonthlyUniverseModel.create({ _id: month, publishedAt: now, members: [{ instrumentId: 'NSE:999000', isin: 'TEST', source: 'scan' }] });
    await QualificationRunModel.create({ _id: 'latest', month, cutoff: now, status: 'completed', qualified: 0, unavailable: 20, total: 20, processed: 20 });
    await StrategyModel.create({ _id: 'strategy', name: 'Trend', revision: 3 });
    await PaperSessionModel.create({ _id: 'account', strategyId: 'strategy', strategy: { name: 'Trend', revision: 1 }, mode: 'automatic', initialPaise: 100000, cashPaise: 90500, active: true, entriesPaused: false, createdAt: now });
    await PaperPositionModel.create({ _id: 'held', sessionId: 'account', instrumentId: 'NSE:999000', symbol: 'TEST', quantity: 1, entryPaise: 10000, costPaise: 10000, openedAt: now });
    await BacktestRunModel.create({ _id: 'report', strategy: { _id: 'strategy', name: 'Trend', revision: 2 }, config: { from: '2025-01-01', to: '2026-01-01' }, createdAt: now, status: 'completed' });
    await PaperSignalModel.create({ _id: 'today', sessionId: 'account', instrumentId: 'NSE:999000', side: 'BUY', createdAt: now, barEnd: now });
    await PaperSignalModel.create({ _id: 'older', sessionId: 'account', instrumentId: 'NSE:999000', side: 'SELL', createdAt: '2025-01-01T05:00:00Z', barEnd: '2025-01-01T05:00:00Z' });
    const { dashboardState } = await import('../src/modules/dashboard/services/dashboard.service.js');
    const before = JSON.stringify(await PaperSessionModel.find().lean());
    const data = await dashboardState();
    assert.equal(data.qualification.count, 1); assert.equal(data.qualification.latestScan?.qualified, 0);
    assert.equal(data.paper.realizedPaise, 500); assert.equal(data.paper.unrealizedPaise, null); assert.equal(data.paper.totalPaise, null);
    assert.equal(data.paper.missingMarks, 1); assert.equal(data.paper.sessions[0].revision, 1); assert.equal(data.paper.sessions[0].currentRevision, 3);
    assert.equal(data.backtests[0].revision, 2); assert.equal(data.backtests[0].currentRevision, 3);
    assert.equal(data.signalsToday, 1); assert.equal(data.signals.length, 2);
    assert.equal(JSON.stringify(await PaperSessionModel.find().lean()), before);
    await PaperSignalModel.insertMany(Array.from({ length: 30 }, (_, i) => ({ _id: `filtered-${i}`, sessionId: 'account', instrumentId: 'NSE:999000', side: i % 2 ? 'BUY' : 'SELL', createdAt: now, barEnd: now })));
    await BacktestRunModel.insertMany(Array.from({ length: 15 }, (_, i) => ({ _id: `extra-${i}`, strategy: { _id: 'strategy', name: 'Trend', revision: 2 }, config: { from: '2025-01-01', to: '2026-01-01' }, createdAt: now, status: 'completed' })));
    await WatchlistModel.insertMany([{ _id: 'older', name: 'Older list', ids: [], updatedAt: '2025-01-01' }, { _id: 'newer', name: 'Newer list', ids: [], updatedAt: now }]);
    await saveDashboardPreferences({ revision: 0, settings: { ...defaultDashboardPreferences, signalSide: 'SELL', signalCount: 10, backtestCount: 12, watchlistMode: 'selected', watchlistIds: ['older', 'newer'], indexIds: ['nse:nifty-100'] } });
    const customized = await dashboardState();
    assert.equal(customized.signals.length, 10); assert.equal(customized.signals.every(signal => signal.side === 'SELL'), true);
    assert.equal(customized.backtests.length, 12); assert.deepEqual(customized.watchlists.map(list => list.id), ['older', 'newer']);
    assert.deepEqual(customized.preferences.indexIds, ['nse:nifty-100']);
    await WatchlistModel.deleteOne({ _id: 'older' });
    assert.deepEqual((await dashboardState()).watchlists.map(list => list.id), ['newer']);
    assert.equal(JSON.stringify(await PaperSessionModel.find().lean()), before);
    await IndexCacheModel.create({ _id: 'BSE', quotes: [], attemptedAt: '2026-09-29T09:00:00Z' });
    await IndexChartModel.create({ _id: 'bse:bse-sensex', points: [{ time: Date.parse('2026-09-29T09:00:00Z'), value: 70000 }], fetchedAt: '2026-09-29T09:00:00Z', sourceUrl: 'https://www.bseindices.com' });
    const { indexQuotes, indexChart } = await import('../src/modules/market-indices/services/index.service.js');
    t.mock.timers.enable({ apis: ['Date'], now: new Date('2026-10-02T10:00:00+05:30') });
    const saved = await indexQuotes();
    assert.equal(saved.market.reason, 'Market holiday'); assert.equal(saved.sources.every(s => !s.refreshing), true);
    const chart = await indexChart('bse:bse-sensex') as { points: unknown[] };
    assert.equal(chart.points.length, 1);
    t.mock.timers.setTime(Date.parse('2026-10-03T10:00:00+05:30'));
    await indexQuotes(); await indexChart('bse:bse-sensex');
    t.mock.timers.setTime(Date.parse('2026-10-05T15:30:00+05:30'));
    await indexQuotes(); await indexChart('bse:bse-sensex');
    assert.equal(refreshLocks, 0); assert.equal(requests, 0);
  } finally {
    t.mock.timers.reset(); axios.defaults.adapter = adapter;
    if (mongoose.connection.readyState === 1 && mongoose.connection.name === name && /^quantforge_test_[a-f0-9]{32}$/.test(name)) await mongoose.connection.dropDatabase();
    await mongoose.disconnect(); await jobs.close(); redis.disconnect();
  }
});
