import { after, test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import mongoose from 'mongoose';
import { env } from '../src/config/env.js';
import { connectDatabase, disconnectDatabase } from '../src/shared/database.js';
import { redis, jobs } from '../src/shared/redis.js';
import { instruments } from '../src/modules/market-data/repository.js';
import { ConnectionModel } from '../src/modules/connections/models/connection.model.js';
import { MonthlyUniverseModel } from '../src/modules/qualification/models/qualification.model.js';
import { currentMonth } from '../src/modules/qualification/services/universe.service.js';
import { StrategyModel } from '../src/modules/strategies/models/strategy.model.js';
import { PaperSessionModel, PaperPositionModel, PaperOrderModel } from '../src/modules/paper-trading/models/paper.model.js';
import { createPaperSession, pauseEntries, stopPaperSession } from '../src/modules/paper-trading/services/paper.service.js';
import { FeedSettingsModel } from '../src/modules/market-feed/models/feed-settings.model.js';
import { syncPaperSubscriptions, updatePaperSubscriptions } from '../src/modules/market-feed/services/paper-subscriptions.service.js';

after(async () => { await jobs.waitUntilReady(); await jobs.close(); if (redis.status !== 'end') await redis.quit(); });
test('paper sessions own automatic subscriptions, recovery and held-position coverage', { skip: process.env.RUN_DB_TESTS !== '1' }, async () => {
  const name = `quantforge_test_${randomUUID().replaceAll('-', '')}`;
  const uri = new URL(env.MONGODB_URI); uri.pathname = '/' + name; env.MONGODB_URI = uri.toString();
  const oldClient = process.env.DHAN_CLIENT_ID;
  process.env.DHAN_CLIENT_ID = 'fixture';
  const saved = () => FeedSettingsModel.findById('primary').lean().orFail();
  const subscriptionIds = async () => (await saved()).request!.instruments.map(s => s.id);
  const publish = async (ids: string[]) => MonthlyUniverseModel.updateOne({ _id: currentMonth() }, { $set: { members: ids.map(instrumentId => ({ instrumentId, source: 'scan' })) } }, { upsert: true });
  try {
    await connectDatabase(); assert.equal(mongoose.connection.name, name);
    await instruments.insertMany(Array.from({ length: 205 }, (_, n) => ({ _id: `NSE:${n + 1}`, exchange: 'NSE', securityId: String(n + 1), symbol: `TEST${n + 1}`, isin: `TEST${n + 1}`, active: true })));
    await ConnectionModel.create({ _id: 'dhan', status: 'connected', expiresAt: new Date(Date.now() + 3600000).toISOString() });
    await publish(['NSE:1', 'NSE:2', 'NSE:3']);
    await FeedSettingsModel.create({ _id: 'primary', enabled: false });
    const strategy = await StrategyModel.create({ _id: randomUUID(), risk: { initialCapital: 100000 }, revision: 1 });
    const session = await createPaperSession({ strategyId: strategy._id, ids: ['NSE:1', 'NSE:3'], mode: 'confirmation' });
    assert.equal((await saved()).enabled, true, 'Starting monitoring connects automatically without a separate feed action');
    assert.deepEqual(await subscriptionIds(), ['NSE:1', 'NSE:3']);
    const beforeHolding = (await saved()).request!.id;
    await PaperPositionModel.create({ _id: 'priority-only', sessionId: session._id, instrumentId: 'NSE:3', quantity: 1 });
    await syncPaperSubscriptions();
    assert.equal((await saved()).request!.id, beforeHolding, 'A holding changes priority without disconnecting the same subscription set');
    await PaperPositionModel.deleteOne({ _id: 'priority-only' });
    await PaperSessionModel.create({ _id: 'second', strategyId: randomUUID(), active: true, ids: ['NSE:2'], entriesPaused: false });
    await PaperPositionModel.create({ _id: 'held', sessionId: session._id, instrumentId: 'NSE:3', quantity: 5 });
    await PaperOrderModel.create({ _id: 'pending', sessionId: session._id, instrumentId: 'NSE:4', status: 'pending', expiresAt: new Date(Date.now() + 60000).toISOString() });
    await publish(['NSE:1', 'NSE:2']);
    await syncPaperSubscriptions();
    assert.deepEqual(await subscriptionIds(), ['NSE:3', 'NSE:4', 'NSE:1', 'NSE:2'], 'Held stocks and pending orders remain subscribed outside the qualified list');
    const stable = await saved();
    await Promise.all([syncPaperSubscriptions(), syncPaperSubscriptions()]);
    assert.equal((await saved()).request?.id, stable.request?.id, 'Identical demand does not reconnect on every poll');
    assert.equal((await saved()).revision, stable.revision);
    await pauseEntries(session._id, true);
    assert.ok((await subscriptionIds()).includes('NSE:1'), 'Pausing automatic buys retains quotes for manual intervention');
    await FeedSettingsModel.updateOne({ _id: 'primary' }, { $set: { automationPaused: true, enabled: false }, $inc: { revision: 1 } });
    await syncPaperSubscriptions();
    assert.equal((await saved()).enabled, false, 'Explicit feed pause survives background reconciliation');
    await pauseEntries(session._id, false);
    assert.equal((await saved()).enabled, true, 'Resuming monitoring automatically resumes its feed');
    await FeedSettingsModel.updateOne({ _id: 'primary' }, { $set: { 'request.provider': 'dhan' }, $inc: { revision: 1 } });
    await ConnectionModel.updateOne({ _id: 'dhan' }, { $set: { status: 'expired' } });
    await syncPaperSubscriptions();
    assert.equal((await saved()).automation?.state, 'blocked');
    assert.equal((await saved()).enabled, false);
    await ConnectionModel.updateOne({ _id: 'dhan' }, { $set: { status: 'connected' } });
    await syncPaperSubscriptions();
    assert.equal((await saved()).enabled, true, 'Credential recovery needs no new session or connect click');
    await PaperPositionModel.deleteMany({}); await PaperOrderModel.deleteMany({});
    await stopPaperSession(session._id);
    assert.deepEqual(await subscriptionIds(), ['NSE:2'], 'Stopping one session preserves the other session');
    await stopPaperSession('second');
    assert.equal((await saved()).enabled, false, 'No paper or manual demand leaves the feed idle');
    // Legacy manual subscriptions remain independent of automatic demand.
    await FeedSettingsModel.deleteMany({});
    await FeedSettingsModel.create({ _id: 'primary', enabled: true, request: { id: 'legacy', provider: 'dhan', instruments: [{ id: 'NSE:5', symbol: 'TEST5', exchange: 'NSE', securityId: '5' }] } });
    await syncPaperSubscriptions();
    assert.deepEqual(await subscriptionIds(), ['NSE:5']);
    assert.equal((await saved()).manualEnabled, true);
    await PaperSessionModel.updateOne({ _id: 'second' }, { $set: { active: true, ids: undefined }, $unset: { ids: 1 } });
    const all = Array.from({ length: 205 }, (_, n) => `NSE:${n + 1}`);
    await publish(all);
    await PaperPositionModel.create({ _id: 'last-held', sessionId: 'second', instrumentId: 'NSE:205', quantity: 5 });
    await updatePaperSubscriptions();
    assert.equal((await subscriptionIds()).length, 205);
    assert.equal((await subscriptionIds())[0], 'NSE:205', 'Held-position exits take priority when capacity is exhausted');
    assert.equal((await saved()).automation?.unavailableIds.length, 0);
    assert.equal((await saved()).automation?.state, 'scheduled');
  } finally {
    if (oldClient === undefined) delete process.env.DHAN_CLIENT_ID; else process.env.DHAN_CLIENT_ID = oldClient;
    if (mongoose.connection.readyState === 1 && mongoose.connection.name === name && /^quantforge_test_[a-f0-9]{32}$/.test(name)) await mongoose.connection.dropDatabase();
    await disconnectDatabase();
  }
});
