import { after, test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import mongoose from 'mongoose';
import { env } from '../src/config/env.js';
import { connectDatabase,disconnectDatabase } from '../src/shared/database.js';
import { jobs,redis } from '../src/shared/redis.js';
import { instruments,storedCandles } from '../src/modules/market-data/repository.js';
import { PaperOrderModel,PaperObservationModel,PaperPositionModel,PaperSessionModel,PaperSignalModel } from '../src/modules/paper-trading/models/paper.model.js';
import { StrategyModel } from '../src/modules/strategies/models/strategy.model.js';
import { BacktestRunModel } from '../src/modules/backtesting/models/backtest.model.js';
import { MonthlyUniverseModel } from '../src/modules/qualification/models/qualification.model.js';
import { currentMonth } from '../src/modules/qualification/services/universe.service.js';
import { evaluatePaperStrategies } from '../src/modules/paper-trading/services/runner.service.js';
import { configurePaperSession,createPaperSession,paperOrderHistory } from '../src/modules/paper-trading/services/paper.service.js';
import { fillPaperOrder } from '../src/modules/paper-trading/services/fill.service.js';
import { orderEstimate } from '../src/modules/paper-trading/services/order-estimate.js';
after(async()=>{await jobs.waitUntilReady();await jobs.close();if(redis.status!=='end')await redis.quit();});
test('signals are independent of paper orders; backtest handoff preserves rules; sizing and history are usable', {skip:process.env.RUN_DB_TESTS!=='1'},async()=>{
 const name=`quantforge_test_${randomUUID().replaceAll('-','')}`,uri=new URL(env.MONGODB_URI);uri.pathname='/'+name;env.MONGODB_URI=uri.toString();
 try{
  await connectDatabase();assert.equal(mongoose.connection.name,name);
  const rule=(side:string)=>({tier:'tactical',side,cadence:'daily',logic:'AND',groups:[{logic:'AND',conditions:[{left:'close',leftFrame:'1d',operator:'gt',rightType:'value',value:50}]}]});
  const strategy=await StrategyModel.create({_id:randomUUID(),name:'Fixture',revision:1,entry:rule('BUY'),exit:rule('SELL'),risk:{initialCapital:100000,riskPercent:1,maxPositions:4,timeframe:'1d',stopMode:'fixed',stopPercent:10,atrPeriod:14,atrMultiplier:2,targetR:5,overnight:true,slippagePercent:0,feePercent:0}});
  await instruments.create({_id:'NSE:1',symbol:'FIXTURE',exchange:'NSE',securityId:'1',isin:'FIXTURE',active:true});
  await MonthlyUniverseModel.create({_id:currentMonth(),members:[{instrumentId:'NSE:1',source:'scan'}]});
  const runId=randomUUID();await BacktestRunModel.create({_id:runId,status:'completed',strategy,config:{ids:['NSE:1']}});
  const session=await createPaperSession({strategyId:strategy._id,ids:['NSE:1'],mode:'signals',sourceBacktestId:runId,expectedRevision:1});
  await PaperSessionModel.updateOne({_id:session._id},{$set:{createdAt:'2026-09-25T03:00:00.000Z'}});
  const candle=(day:string)=>({instrumentId:'NSE:1',interval:'1d' as const,time:day+'T03:45:00.000Z',open:100,high:105,low:95,close:100,volume:1000});
  await storedCandles.create(candle('2026-09-25'));
  await evaluatePaperStrategies(Date.parse('2026-09-25T11:00:00Z'));
  assert.equal(await PaperSignalModel.countDocuments(),2,'Signals-only watches both buy and sell rules');
  assert.equal(await PaperOrderModel.countDocuments(),0,'Watching rules must never submit orders');
  assert.equal((await PaperObservationModel.findOne())?.entry.matched,true);
  assert.equal((await PaperSignalModel.findOne())?.referencePrice,100);
  await evaluatePaperStrategies(Date.parse('2026-09-25T11:01:00Z'));
  assert.equal(await PaperSignalModel.countDocuments(),2,'Repeated checks must not duplicate alerts');
  await configurePaperSession(session._id,{mode:'automatic'});
  await evaluatePaperStrategies(Date.parse('2026-09-25T11:02:00Z'));
  assert.equal(await PaperOrderModel.countDocuments(),0,'Changing mode must not trade an old alert');
  await storedCandles.create(candle('2026-09-28'));
  await evaluatePaperStrategies(Date.parse('2026-09-28T11:00:00Z'));
  const order=(await PaperOrderModel.findOne().lean())!;
  assert.equal(order.status,'pending');
  const at='2026-09-29T03:46:00.000Z',quote={instrumentId:'NSE:1',symbol:'FIXTURE',exchange:'NSE' as const,price:100,at,receivedAt:at,source:'dhan' as const,session:'fixture',cumulativeVolume:1000};
  const saved=(await PaperSessionModel.findById(session._id).lean())!;
  const estimate=orderEstimate(order,saved,[],quote);
  assert.deepEqual({quantity:estimate.quantity,stop:estimate.stopPaise,target:estimate.targetPaise},{quantity:100,stop:9000,target:15000});
  await fillPaperOrder(order._id,quote,Date.parse(at));
  assert.equal((await PaperPositionModel.findOne())?.quantity,estimate.quantity,'Displayed risk sizing and actual fill use the same ceilings');
  await assert.rejects(configurePaperSession(session._id,{mode:'signals'}),/Close held paper positions/);
  await assert.rejects(configurePaperSession(session._id,{ids:['NSE:2']}),/currently qualified/);
  await StrategyModel.updateOne({_id:strategy._id},{$set:{revision:2}});
  await assert.rejects(createPaperSession({strategyId:strategy._id,ids:['NSE:1'],mode:'automatic',sourceBacktestId:runId}),/current saved strategy/);
  const when='2026-09-28T00:00:00.000Z';
  await PaperOrderModel.insertMany(Array.from({length:25},()=>({_id:randomUUID(),sessionId:'old',instrumentId:'NSE:1',status:'filled',side:'BUY',quantity:1,createdAt:when,fillPaise:10000})));
  const first=await paperOrderHistory({sessionId:'old'}),second=await paperOrderHistory({sessionId:'old',...first.next!});
  assert.equal(first.items.length,20);assert.equal(second.items.length,5);assert.equal(new Set([...first.items,...second.items].map(o=>o._id)).size,25,'Pagination must not lose same-time fills');
 }finally{if(mongoose.connection.readyState===1&&mongoose.connection.name===name&&/^quantforge_test_[a-f0-9]{32}$/.test(name))await mongoose.connection.dropDatabase();await disconnectDatabase();}
});
