import type { Strategy } from "../types";
export const mockStrategies: Strategy[] = [
  {
    id: "momentum",
    name: "Momentum Edge V4",
    description: "TF: 5m · EMA/RSI Confluence",
    mode: "LIVE",
    segment: "NSE EQ",
    signals: 6,
    clients: 611,
    capital: 48500000,
    pnl: 412300,
    roi: 1.8,
    drawdown: -2.1,
    health: 99.8,
  },
  {
    id: "orb",
    name: "Opening Range Breakout",
    description: "TF: 15m · Volume Spikes",
    mode: "LIVE",
    segment: "BANKNIFTY OPT",
    signals: 4,
    clients: 382,
    capital: 29000000,
    pnl: 284500,
    roi: 2.4,
    drawdown: -3.4,
    health: 99.2,
  },
  {
    id: "trend",
    name: "Trend Rider Multicap",
    description: "TF: Daily · SuperTrend Multi",
    mode: "PAPER",
    segment: "NIFTY 500",
    signals: 8,
    clients: 140,
    capital: 11000000,
    pnl: 98200,
    roi: 0.9,
    drawdown: -1.8,
    health: 100,
  },
  {
    id: "straddle",
    name: "Nifty Straddle Gamma",
    description: "TF: Tick · Delta Neutral Auto",
    mode: "LIVE",
    segment: "NIFTY OPT",
    signals: 2,
    clients: 118,
    capital: 14500000,
    pnl: 67410,
    roi: 0.6,
    drawdown: -1.2,
    health: 98.9,
  },
  {
    id: "vwap",
    name: "Vwap Mean Reversion",
    description: "TF: 3m · 2-Sigma Band Bounce",
    mode: "HALTED",
    segment: "NSE EQ",
    signals: 1,
    clients: 32,
    capital: 3500000,
    pnl: -12400,
    roi: -0.4,
    drawdown: -5.1,
    health: 0,
  },
];
