import {useCallback,useEffect,useState} from 'react';
import {Alert,Button,Checkbox,InputNumber,Space,Spin,Tag} from 'antd';
import {apiClient} from '../../../services/apiClient';
import type {PaperPosition} from '../hooks/useBackendPaper';
interface Detail {position:PaperPosition;history:{_id:string;at:string;action:string;before:{stopPaise:number;targets:number[]};after:{stopPaise:number;targets:number[]}}[]}
const money=(p:number)=>`INR ${(p/100).toFixed(2)}`;
export function ManagePositionExits({position,onSaved}:{position:PaperPosition;onSaved:()=>Promise<void>}){
 const [detail,setDetail]=useState<Detail>(),[stop,setStop]=useState<number|null>(null),[targets,setTargets]=useState<(number|null)[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(true),[ack,setAck]=useState(false),[restore,setRestore]=useState(false);
 const load=useCallback((signal?:AbortSignal)=>apiClient.get<Detail>(`/paper/positions/${encodeURIComponent(position._id)}/exits`,{signal}).then(({data:d})=>{if(signal?.aborted)return;setError('');setDetail(d);setStop(d.position.stopPaise/100);setTargets(d.position.targets?.map(t=>t.pricePaise/100)??[d.position.targetPaise/100]);setAck(false);setRestore(false);}).catch(e=>{if(!signal?.aborted)setError(e.message);}).finally(()=>{if(!signal?.aborted)setBusy(false);}),[position._id]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);
 const p=detail?.position;
 const chooseRestore=()=>{if(!p?.exitControl)return;setRestore(true);setStop(p.exitControl.strategyStopPaise/100);setTargets((p.targets?.map(t=>t.pricePaise)??[p.targetPaise]).map((v,i)=>(p.targets?.[i]?.completed?v:p.exitControl!.strategyTargetPrices[i])/100));setAck(false);};
 const save=async()=>{if(!p)return;setBusy(true);setError('');try{await apiClient.patch(`/paper/positions/${encodeURIComponent(p._id)}/exits`,{expectedOpenedAt:p.openedAt,expectedQuantity:p.quantity,expectedStopPaise:p.stopPaise,expectedStrategyStopPaise:p.exitControl?.strategyStopPaise??p.stopPaise,expectedRevision:p.exitControl?.revision??0,action:restore?'restore':'edit',...(restore?{}:{stop,targets}),acknowledgeRisk:ack});await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Space orientation="vertical" size={16} style={{width:'100%'}}>{error&&<Alert type="error" showIcon title={error}/>}<Button onClick={()=>{setBusy(true);void load();}} disabled={busy}>Refresh current levels</Button>{!p?(busy?<Spin/>:<p>Position details are unavailable. Refresh to try again.</p>):<><p><strong>{p.symbol}</strong> | {p.quantity} shares remaining | Entry {money(p.entryPaise)}</p><p>Changes affect this position only. New automatic entries pause after applying; existing position protection continues. Filled exits and target quantities stay unchanged.</p>
 {p.exitControl&&(p.exitControl.stopOverridden||p.exitControl.targetOverrides.some(Boolean))&&<Tag color="gold">Manual exit overrides active</Tag>}
 <label>Stop-loss price (INR)<br/><InputNumber aria-label="Position stop price" min={0.01} precision={2} value={stop} disabled={busy} onChange={v=>{setStop(v);setRestore(false);setAck(false);}}/></label>
 <small>Current {money(p.stopPaise)} | Strategy {money(p.exitControl?.strategyStopPaise??p.stopPaise)}</small>
 {targets.map((value,i)=><label key={i}>Target {i+1} {p.targets?.[i]?.completed?'(already completed)':`(${i===targets.length-1?'remaining':Math.min(p.quantity,p.targets?.[i]?.quantity??p.quantity)} shares)`}<br/><InputNumber aria-label={`Position target ${i+1}`} min={0.01} precision={2} value={value} disabled={busy||p.targets?.[i]?.completed} onChange={v=>{setTargets(old=>old.map((x,j)=>i===j?v:x));setRestore(false);setAck(false);}}/><small> Strategy {money(p.exitControl?.strategyTargetPrices[i]??p.targets?.[i]?.pricePaise??p.targetPaise)}</small></label>)}
 {stop!=null&&<Alert type={stop*100<p.stopPaise?'warning':'info'} title={`Entry-to-stop downside before costs: ${money(Math.max(0,p.entryPaise-Math.round(stop*100))*p.quantity)}`} description={stop*100<p.stopPaise?'You are lowering the stop. This increases downside or gives back protected gains.':'Gaps and execution costs can cause a larger loss than this estimate.'}/>}
 {restore&&<Alert type="info" title="Restoring the current strategy levels" description="Trailing and breakeven tracking resume from the strategy state. Completed partial exits are preserved."/>}
 <Checkbox checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}>I reviewed these levels. A crossed level may trigger on the next fresh eligible quote; prices may have changed since this view loaded.</Checkbox>
 <Space wrap><Button disabled={busy||!p.exitControl} onClick={chooseRestore}>Restore strategy levels</Button><Button type="primary" loading={busy} disabled={!ack||stop==null||targets.some(v=>v==null)} onClick={()=>void save()}>{restore?'Apply restored levels':'Apply changes'}</Button></Space>
 <details><summary>Exit changes ({detail.history.length} latest)</summary>{detail.history.map(h=><p key={h._id}>{new Date(h.at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} | {h.action} | SL {money(h.before.stopPaise)} to {money(h.after.stopPaise)} | Targets {h.after.targets.map(money).join(', ')}</p>)}</details>
 </>}</Space>;
}
