import { orderedBacktestStocks, BACKTEST_STOCK_LIMIT } from '../../modules/strategies/utils/backtestSelection';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {Alert,Button,Checkbox,Input,Select,Space,Tag} from 'antd';
import {useNavigate} from 'react-router-dom';
import {apiClient} from '../../services/apiClient';
import type {ScopedStock} from '../../modules/strategies/hooks/useQualifiedStockScope';
import type {BackendBacktest} from '../../modules/backtesting/types/backend';
export interface AssistantWorkflow {kind:'backtest'|'paper'|'qualification';revision:number;strategyId?:string;name?:string;cadence?:string;horizon?:'intraday'|'swing'|'long-term';capital?:number;sourceReportId?:string}
export interface BacktestChatState {from:string;to:string;exchange:string;universe:'current'|'historical';ack:boolean;ids:string[];reportId?:string;mode:'signals'|'confirmation'|'automatic';started:boolean}
type Stock=ScopedStock;
const dateBefore=(days:number)=>new Date(Date.now()+330*60000-days*86400000).toISOString().slice(0,10);
export default function AssistantBacktestRun({workflow,visible,onExplain,initialState,onStateChange,onEvent}:{workflow:AssistantWorkflow;visible:boolean;onExplain:(id:string)=>void;initialState?:BacktestChatState;onStateChange?:(state:BacktestChatState)=>void;onEvent?:(text:string)=>void}){
 const horizon=workflow.horizon??(workflow.cadence==='daily'?'swing':'intraday');
 const navigate=useNavigate(),lock=useRef(false),request=useRef<{key:string;id:string}|undefined>(undefined);
 const [from,setFrom]=useState(()=>initialState?.from??dateBefore(workflow.cadence==='daily'?365:30)),[to,setTo]=useState(()=>initialState?.to??dateBefore(1));
 const [exchange,setExchange]=useState(initialState?.exchange??'NSE'),[universe,setUniverse]=useState<'current'|'historical'>(initialState?.universe??'current'),[ack,setAck]=useState(initialState?.ack??false);
 const [stocks,setStocks]=useState<Stock[]>([]),[ids,setIds]=useState<string[]>(initialState?.ids??[]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [reportId,setReportId]=useState(initialState?.reportId??workflow.sourceReportId),[report,setReport]=useState<BackendBacktest>();
 const [mode,setMode]=useState<'signals'|'confirmation'|'automatic'>(initialState?.mode??'signals'),[started,setStarted]=useState(initialState?.started??false);
 const scope=JSON.stringify([exchange,universe,from,to]);
 const selection=useRef({scope,ids,loaded:!!initialState});
 const stateCallback=useRef(onStateChange);useLayoutEffect(()=>{stateCallback.current=onStateChange;},[onStateChange]);
 useEffect(()=>{if(!loading)stateCallback.current?.({from,to,exchange,universe,ack,ids,reportId,mode,started});},[from,to,exchange,universe,ack,ids,reportId,mode,started,loading]);
 // Clear the previous universe before fetching a new scope so stale stock IDs cannot be submitted.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(reportId||!visible)return;const abort=new AbortController();setLoading(true);setStocks([]);if(selection.current.scope!==scope)setIds([]);setError('');
 void apiClient.get<{stocks:Stock[]}>('/backtests/universe',{params:{universe,includeManual:'true',suitability:'true',from,to},signal:abort.signal}).then(({data})=>{if(abort.signal.aborted)return;const list=data.stocks.filter(s=>exchange==='all'||s.exchange===exchange);setStocks(list);const chosen=selection.current.loaded&&selection.current.scope===scope?selection.current.ids.filter(id=>list.some(stock=>stock._id===id)):orderedBacktestStocks(universe==='historical'?list:list.filter(s=>s.suitability?.profiles.some(p=>p.horizon===horizon&&p.status==='matched')),horizon,universe==='historical').slice(0,BACKTEST_STOCK_LIMIT).map(s=>s._id);selection.current={scope,ids:chosen,loaded:true};setIds(chosen);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();
 },[exchange,universe,from,to,visible,reportId,horizon,scope]);
 useEffect(()=>{if(!reportId||!visible)return;const abort=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const {data}=await apiClient.get<BackendBacktest>(`/backtests/${reportId}`,{signal:abort.signal});if(abort.signal.aborted)return;setReport(data);setError('');if(data.status==='queued'||data.status==='running')timer=setTimeout(()=>void poll(),2500);}catch(e){if(!abort.signal.aborted){setError(e instanceof Error?e.message:'Could not refresh report');timer=setTimeout(()=>void poll(),5000);}}};void poll();return()=>{abort.abort();clearTimeout(timer);};},[reportId,visible]);
 const run=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const body={strategyId:workflow.strategyId,expectedRevision:workflow.revision,from,to,universe,includeManual:true,acknowledgeSelectionBias:ack,dataPolicy:'ready',ids};const key=JSON.stringify(body);if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};const {data}=await apiClient.post<{id:string}>('/backtests',{...body,requestId:request.current.id});setReportId(data.id);onEvent?.(`Backtest queued for ${workflow.name??'strategy'} revision ${workflow.revision}: ${from} to ${to}, ${ids.length} stocks (${exchange}). Report ID: ${data.id}.`);}catch(e){setError(e instanceof Error?e.message:'Could not queue backtest');}finally{lock.current=false;setBusy(false);}};
 const result=report?.result;
 const incomplete=!!result&&(!!result.historyQuality?.missingMinutes||!!result.historyQuality?.missingExitSessions||result.unavailableDecisions>(result.warmupDecisions??0)||!!result.unreadyInstruments?.length);
 const ready=report?.status==='completed'&&!!result&&!incomplete&&(!report.config.dataPolicy||!!report.selectionAudit)&&report.strategy.revision===workflow.revision;
 const start=async()=>{if(lock.current||!ready)return;lock.current=true;setBusy(true);setError('');try{await apiClient.post('/paper/sessions',{strategyId:workflow.strategyId,expectedRevision:workflow.revision,sourceBacktestId:reportId,ids:report.config.ids,mode});setStarted(true);onEvent?.(`Paper monitoring started from backtest ${reportId}, in ${mode} mode.`);}catch(e){setError(e instanceof Error?e.message:'Could not start paper session');}finally{lock.current=false;setBusy(false);}};
 return <section aria-label="Assistant backtest workflow" style={{padding:16,border:'1px solid var(--ant-color-border)',borderRadius:10,marginTop:12}}>
 <strong>{workflow.name} <Tag>Revision {workflow.revision}</Tag></strong><p>Backtest first, then choose how to monitor it with paper trading.</p>
 {!reportId&&<><Space wrap><label>From<Input aria-label="Backtest from" type="date" value={from} max={to} disabled={busy} onChange={e=>setFrom(e.target.value)}/></label><label>Through<Input aria-label="Backtest through" type="date" value={to} max={dateBefore(1)} disabled={busy} onChange={e=>setTo(e.target.value)}/></label><Select aria-label="Exchange" value={exchange} disabled={busy} onChange={setExchange} options={[{value:'NSE',label:'NSE only'},{value:'BSE',label:'BSE only'},{value:'all',label:'NSE and BSE'}]}/><Select aria-label="Qualified list" value={universe} disabled={busy} onChange={setUniverse} options={[{value:'current',label:'Current qualified list'},{value:'historical',label:'Qualified at the time'}]}/></Space>
 <p>Stocks with required history are checked before replay. Manual additions are included. Up to 200 stocks per run.</p>
 <Select aria-label="Stocks to backtest" mode="multiple" maxCount={BACKTEST_STOCK_LIMIT} style={{width:'100%'}} value={ids} onChange={next=>{selection.current={scope,ids:next,loaded:true};setIds(next);}} loading={loading} disabled={busy||loading} maxTagCount={3} optionFilterProp="label" options={stocks.map(s=>({value:s._id,label:`${s.symbol} / ${s.exchange}`}))}/>
 <p>{ids.length} selected / {stocks.length} available{ids.length>=BACKTEST_STOCK_LIMIT&&" - Limit reached: remove a selected stock to add another."}</p>
 {!loading&&<details open><summary>Why these stocks? View selection evidence</summary><p>{universe==='historical'?'Historical qualification is used. Current suitability is not applied retrospectively.':`Default selection: stocks matching the ${horizon} research profile. These checks assess trading characteristics, not whether the current buy rule passes or profit probability.`} If more than 200 match, the first 200 by symbol are selected; that ordering is not a ranking of expected returns. You can adjust the selection above.</p>
 {universe==='current'&&!stocks.some(s=>s.suitability?.profiles.some(p=>p.horizon===horizon&&p.status==='matched'))&&<Alert type="warning" title="No stocks currently have a confirmed matching profile" description="Inspect the missing or failed checks below. Refresh suitability inputs in Qualification, or explicitly choose stocks for exploratory testing."/>}
 <div style={{maxHeight:280,overflow:'auto'}}>{stocks.map(stock=>{const profile=stock.suitability?.profiles.find(p=>p.horizon===horizon);return <details key={stock._id}><summary>{ids.includes(stock._id)?'Selected':'Not selected'}: {stock.symbol} / {stock.exchange} - {universe==='historical'?'historical qualification':profile?.status??'needs data'}</summary><p>{stock.source==='manual'?'Manually added to qualification.':'From qualification scan.'} {stock.suitability?.assessedAt&&`Assessed: ${stock.suitability.assessedAt}`}</p>{universe==='current'&&(profile?.checks.length?<ul>{profile.checks.map((check,index)=><li key={index}>{check.label}: {check.rule} ? {check.status}; value: {check.value===null?'unavailable':`${check.value} ${check.unit}`}{check.asOf&&` (as of ${check.asOf})`}{check.reason&&` ? ${check.reason}`}</li>)}</ul>:<p>Suitability inputs are unavailable; no fit claim can be made.</p>)}</details>;})}</div></details>}

 {universe==='current'&&<Checkbox checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}>I understand today's qualified list uses information unavailable in the past. This is research, not a historical stock-selection test.</Checkbox>}
 <p><Button type="primary" aria-label="Run backtest" loading={busy} disabled={busy||loading||!stocks.length||!ids.length||ids.length>200||!from||!to||from>to||to>dateBefore(1)||(universe==='current'&&!ack)} onClick={()=>void run()}>Run backtest</Button></p></>}
 {reportId&&!report&&<p role="status">Loading backtest...</p>}
 {report&&<><p role="status"><Tag>{report.status}</Tag>{report.stage}{report.stage==='preparing'&&report.progress&&` - ${report.progress.processed} / ${report.progress.total}`}{report.status==='running'&&report.message&&` - ${report.message}`}</p>{report.status==='failed'&&<Alert type="error" title="Backtest failed" description={report.message}/>}
 {result&&<><Space wrap><strong>Net P&amp;L: INR {result.netPnl.toLocaleString('en-IN',{maximumFractionDigits:2})}</strong><span>Return: {result.returnPercent.toFixed(2)}%</span><span>Win rate: {result.winRate===null?'Unavailable':`${result.winRate.toFixed(1)}%`}</span></Space>{incomplete&&<Alert type="warning" title="Data gaps need attention before starting paper trading"/>}<p><Button onClick={()=>onExplain(reportId!)}>Ask AI to explain this report</Button></p></>}
 {(report.status==='failed'||report.status==='completed')&&!started&&<Button disabled={busy} onClick={()=>{request.current=undefined;setReportId(undefined);setReport(undefined);setError('');}}>Set up another test</Button>}
 <Button onClick={()=>navigate(`/strategies?tab=backtests&rule=${workflow.strategyId}`)}>Open full backtest reports</Button>
 {ready&&!started&&<><h3>Continue to paper trading</h3><p>Uses this report's tested stocks and saved revision. The server checks current qualification and active sessions again.</p><Select aria-label="Paper execution mode" value={mode} disabled={busy} style={{width:'100%'}} onChange={setMode} options={[{value:'signals',label:'Signals only - show buy and sell decisions'},{value:'confirmation',label:'Confirm each paper entry'},{value:'automatic',label:'Automatic paper fills under strategy risk limits'}]}/><p>{mode==='signals'?'No paper orders are filled in signals-only mode.':mode==='automatic'?'Starts automatic simulated orders when strategy conditions match.':'Paper entries await your confirmation; protective exits follow the strategy.'} No real orders.</p><Button type="primary" aria-label="Start paper monitoring" disabled={busy} loading={busy} onClick={()=>void start()}>Start paper monitoring</Button></>}
 {started&&<Alert type="success" title="Paper session started" description={<Button onClick={()=>navigate('/paper-trading')}>View paper trading</Button>}/>}</>}
 {error&&<Alert type="error" title="Action not confirmed" description={error}/>}
 </section>;
}
