// Mirrors backend INDEX_SOURCES (index-membership.ts); keep ids in sync.
export const stockIndices = [
  { value: 'nifty-50', label: 'NIFTY 50' },
  { value: 'nifty-next-50', label: 'NIFTY NEXT 50' },
  { value: 'nifty-100', label: 'NIFTY 100' },
  { value: 'nifty-200', label: 'NIFTY 200' },
  { value: 'nifty-500', label: 'NIFTY 500' },
  { value: 'nifty-midcap-150', label: 'NIFTY MIDCAP 150' },
  { value: 'nifty-smallcap-250', label: 'NIFTY SMALLCAP 250' },
  { value: 'nifty-microcap-250', label: 'NIFTY MICROCAP 250' },
  { value: 'nifty-total-market', label: 'NIFTY TOTAL MARKET' },
  { value: 'nifty-bank', label: 'NIFTY BANK' },
  { value: 'nifty-private-bank', label: 'NIFTY PRIVATE BANK' },
  { value: 'nifty-psu-bank', label: 'NIFTY PSU BANK' },
  { value: 'nifty-financial-services', label: 'NIFTY FINANCIAL SERVICES' },
  { value: 'nifty-capital-markets', label: 'NIFTY CAPITAL MARKETS' },
  { value: 'nifty-it', label: 'NIFTY IT' },
  { value: 'nifty-auto', label: 'NIFTY AUTO' },
  { value: 'nifty-pharma', label: 'NIFTY PHARMA' },
  { value: 'nifty-healthcare', label: 'NIFTY HEALTHCARE' },
  { value: 'nifty-fmcg', label: 'NIFTY FMCG' },
  { value: 'nifty-consumer-durables', label: 'NIFTY CONSUMER DURABLES' },
  { value: 'nifty-metal', label: 'NIFTY METAL' },
  { value: 'nifty-realty', label: 'NIFTY REALTY' },
  { value: 'nifty-housing', label: 'NIFTY HOUSING' },
  { value: 'nifty-oil-gas', label: 'NIFTY OIL & GAS' },
  { value: 'nifty-energy', label: 'NIFTY ENERGY' },
  { value: 'nifty-chemicals', label: 'NIFTY CHEMICALS' },
  { value: 'nifty-media', label: 'NIFTY MEDIA' },
  { value: 'nifty-infrastructure', label: 'NIFTY INFRASTRUCTURE' },
  { value: 'nifty-india-defence', label: 'NIFTY INDIA DEFENCE' },
  { value: 'nifty-india-manufacturing', label: 'NIFTY INDIA MANUFACTURING' },
  { value: 'nifty-pse', label: 'NIFTY PSE' },
  { value: 'nifty-cpse', label: 'NIFTY CPSE' },
  { value: 'bse-sensex', label: 'BSE SENSEX' },
  { value: 'bse-100', label: 'BSE 100' },
  { value: 'bse-200', label: 'BSE 200' },
  { value: 'bse-500', label: 'BSE 500' },
  { value: 'bse-bankex', label: 'BSE BANKEX' },
  { value: 'bse-auto', label: 'BSE AUTO' },
  { value: 'bse-it', label: 'BSE Information Technology' },
  { value: 'bse-healthcare', label: 'BSE Healthcare' },
  { value: 'bse-metal', label: 'BSE METAL' },
  { value: 'bse-capital-goods', label: 'BSE CAPITAL GOODS' },
] as const;

export type StockIndex = (typeof stockIndices)[number]['value'];
export const stockIndexLabel = (id: string) => stockIndices.find((index) => index.value === id)?.label ?? id;
