import {create} from 'zustand';
import {apiClient} from '../../../services/apiClient';
import type {SavedStrategy} from '../../strategies/hooks/useBackendStrategies';
export interface MonitoringScope { selectedIds:string[]; eligibleIds:string[]; excludedIds:string[]; heldIds:string[]; monitoredIds:string[]; entryIds:string[] }
export interface ExecutionFeed { automation?:{state:'idle'|'scheduled'|'blocked'|'paused';message:string;paperIds:string[];unavailableIds:string[]}; state:string; message:string; freshIds:string[]; subscribedIds?:string[]; enabled?:boolean; workerRunning?:boolean }
export interface IntradayPlan { date: string; nextOpenAt: string | null; calendarKnown: boolean; continuation: string; phase: string; unfinishedPositions: number; eligibleStocks: number }
export interface PaperSession { intraday?: IntradayPlan;eligibility?:import('../../backtesting/components/BacktestPaperEligibility').EligibilitySettings;dailyLossLimitPercent?:number;maxEntryDeviationPercent?:number;scope?:MonitoringScope;_id:string;strategy:SavedStrategy;ids?:string[];mode:'signals'|'automatic'|'confirmation';sourceBacktestId?:string;cashPaise:number;initialPaise:number;bookedPnlPaise?:number;hasTrades?:boolean;entriesPaused:boolean;active:boolean;message?:string;checkedAt?:string}
export interface PaperPosition {exitControl?:{strategyStopPaise:number;strategyTargetPrices:number[];stopOverridden:boolean;targetOverrides:boolean[];revision:number;changedAt:string};mark?:{pricePaise:number;valuePaise:number;unrealizedPaise:number;at:string;fresh:boolean;source:string};_id:string;sessionId:string;instrumentId:string;symbol:string;quantity:number;initialQuantity?:number;entryPaise:number;stopPaise:number;targetPaise:number;openedAt?:string;initialRiskPaise?:number;trailingActivated?:boolean;breakevenActivated?:boolean;targets?:{pricePaise:number;quantity:number;completed:boolean;filledQuantity?:number}[]}
export interface PaperOrder {_id:string;sessionId:string;instrumentId:string;side:string;quantity:number;source:string;status:string;createdAt:string;reason:string;message?:string;orderType?:'market'|'limit';eligibleAfter?:string;limitPaise?:number;fillPaise?:number;feePaise?:number;entryPaise?:number;entryFeePaise?:number;allocatedCostPaise?:number;realizedPnlPaise?:number;positionOpenedAt?:string;quoteAt?:string;expiresAt?:string;filledAt?:string;amendments?:{at:string;orderType:string;limitPaise?:number}[];estimate?:{pricePaise?:number;quantity?:number;stopPaise?:number;targetPaise?:number;riskPaise?:number;message?:string}}
export interface PaperSignal {_id:string;sessionId:string;instrumentId:string;side:string;barEnd:string;createdAt?:string;expiresAt?:string;referencePrice?:number;checks?:RuleCheck[];message?:string;orderId?:string}
export interface RuleCheck {matched:boolean|null;field:string;missingField?:string;left?:number;right?:number;reason?:string}
export interface PaperObservation {_id:string;sessionId:string;instrumentId:string;barEnd:string|null;checkedAt:string;current:boolean;entry:{matched:boolean|null;checks:RuleCheck[]};exit:{matched:boolean|null;disabled?:boolean;checks:RuleCheck[]};referencePrice?:number}
export interface PaperData {safety?:{halted?:boolean;clock:{state:string;message:string};warnings:string[];notices?:string[]};observations?:PaperObservation[];symbols?:Record<string,string>;sessions:PaperSession[];positions:PaperPosition[];orders:PaperOrder[];signals:PaperSignal[];workerRunning:boolean;feed?:ExecutionFeed;marketOpen?:boolean;history?:{state:string;message?:string;failed?:number;errors?:string[];updatedAt:string}}
interface State {data?:PaperData;error?:string;refresh:()=>Promise<void>}
let refreshing: Promise<void> | null = null;
export const useBackendPaper=create<State>(set=>({refresh:()=>{if(refreshing)return refreshing;refreshing=(async()=>{try{set({data:(await apiClient.get<PaperData>('/paper')).data,error:undefined});}catch(e){set({error:(e as Error).message});}})().finally(()=>{refreshing=null;});return refreshing;}}));
