import { Router } from 'express';
import { z } from 'zod';
import { BacktestRunModel } from '../models/backtest.model.js';
import { queueBacktest } from '../services/backtest.service.js';
import { backtestUniverseOptions } from '../services/universe.service.js';
export const backtestRouter = Router();
backtestRouter.get('/', async (req,res) => { const strategyId = z.string().uuid().optional().parse(req.query.strategyId); res.json(await BacktestRunModel.find(strategyId ? { 'strategy._id': strategyId } : {}).select('-snapshots -result').sort({createdAt:-1}).limit(30).lean()); });
backtestRouter.get('/universe', async (req, res) => { res.json(await backtestUniverseOptions(req.query)); });
backtestRouter.get('/:id', async (req,res) => { res.json(await BacktestRunModel.findById(z.string().uuid().parse(req.params.id)).select('-snapshots').lean()); });
backtestRouter.post('/',async(req,res)=>{res.status(202).json(await queueBacktest(req.body));});
