import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { ZodError } from 'zod';
import { isAllowedFrontendOrigin } from './config/frontend-origin.js';
import { AppError } from './shared/errors.js';
import { databaseReady } from './shared/database.js';
import { redis } from './shared/redis.js';
import { startLocalSession, requireWorkspace } from './middleware/workspace.js';
import { marketDataRouter } from './modules/market-data/routes/market-data.routes.js';
import { connectionRouter } from './modules/connections/routes/connection.routes.js';
import { qualificationRouter } from './modules/qualification/routes/qualification.routes.js';
import { feedRouter } from './modules/market-feed/routes/feed.routes.js';
import { strategyRouter } from './modules/strategies/routes/strategy.routes.js';
import { backtestRouter } from './modules/backtesting/routes/backtest.routes.js';
import { paperRouter } from './modules/paper-trading/routes/paper.routes.js';
import { indexRouter } from './modules/market-indices/routes/index.routes.js';
import { aiRouter } from './modules/ai/routes/ai.routes.js';
import { stockDetailsRouter } from './modules/stock-details/routes/stock-details.routes.js';
export const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: (origin, callback) => callback(null, isAllowedFrontendOrigin(origin)), credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.get('/health', (_req, res) => {
  const ready = databaseReady() && redis.status === 'ready';
  res.status(ready ? 200 : 503).json({ status: ready ? 'ready' : 'unavailable', execution: 'paper-only', database: databaseReady(), redis: redis.status === 'ready' });
});
app.post('/api/session', startLocalSession);
app.use('/api', requireWorkspace);
app.use('/api/market-data', marketDataRouter);
app.use('/api/market-indices', indexRouter);
app.use('/api/connections', connectionRouter);
app.use('/api/qualification', qualificationRouter);
app.use('/api/market-feed', feedRouter);
app.use('/api/strategies', strategyRouter);
app.use('/api/backtests', backtestRouter);
app.use('/api/paper', paperRouter);
app.use('/api/ai', aiRouter);
app.use('/api/stocks', stockDetailsRouter);
app.get('/api/events', async (req, res) => {
  res.set({ 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive', 'X-Accel-Buffering': 'no' });
  res.flushHeaders(); res.write('event: ready\ndata: {}\n\n');
  const subscriber = redis.duplicate();
  subscriber.on('error', () => {});
  subscriber.on('message', (_channel, payload) => { res.write(`data: ${payload}\n\n`); });
  const heartbeat = setInterval(() => res.write(': heartbeat\n\n'), 15_000);
  const close = () => { clearInterval(heartbeat); subscriber.disconnect(); };
  req.on('close', close);
  await subscriber.subscribe('quantforge:events');
});
app.use((_req, _res, next) => next(new AppError(404, 'NOT_FOUND', 'Endpoint not found')));
app.use((error: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  if (res.headersSent) return res.end();
  if (error instanceof ZodError) return res.status(422).json({ code: 'VALIDATION', message: 'Please correct the highlighted values', issues: error.issues.map(x => ({ path: x.path, message: x.message })) });
  if (error instanceof AppError) return res.status(error.status).json({ code: error.code, message: error.message });
  if(error && typeof error==='object' && 'code' in error && error.code===11000)return res.status(409).json({code:'CONFLICT',message:'This item already exists or another action is pending. Refresh before trying again.'});
  res.status(500).json({ code: 'INTERNAL', message: 'The operation failed; no successful result was recorded' });
});
