import { RequestFeedback } from '../../../components/feedback/RequestFeedback';
import { useState } from 'react';
import { Alert, Button, Drawer, Empty, Space, Spin, Tag } from 'antd';
import { ArrowUpOutlined, ArrowDownOutlined, BarChartOutlined, ThunderboltOutlined, BankOutlined, ApartmentOutlined, BlockOutlined, SafetyOutlined, InfoCircleOutlined, ReloadOutlined } from '@ant-design/icons';
import type { DiscoveryGroup, DiscoveryState } from '../types';
import '../../../styles/stock-discovery.css';
import { discoveryNumber, discoveryTime } from '../utils/format';

const icons = [ArrowUpOutlined, ArrowDownOutlined, BarChartOutlined, ThunderboltOutlined, BankOutlined, ApartmentOutlined, BlockOutlined, SafetyOutlined];
const date = (value: string) => new Date(`${value}T12:00:00+05:30`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
export function DiscoveryGroups({ data, error, selected, onSelect, onRefresh }: { data?: DiscoveryState; error?: string; selected?: string; onSelect: (id?: string) => void; onRefresh: () => void }) {
  const [rules, setRules] = useState<DiscoveryGroup>();
  const group = data?.groups?.find(item => item.id === selected);
  return <section className="stock-discovery" aria-label="Discover stocks">
    <div className="discovery-heading"><div><h2>Discover stocks</h2><p>Explore market moves and company filters. See the rules behind every group.</p></div><Button size="small" icon={<ReloadOutlined />} loading={data?.refreshing} onClick={onRefresh}>Refresh groups</Button></div>
    {error && <RequestFeedback type="warning" showIcon title="Discovery groups could not load" description={error} />}
    {!data && !error && <Spin size="small" />}
    {data?.groups?.length ? <>
      <div className="discovery-grid">{data.groups.map((item, i) => { const Icon = icons[i % icons.length]; return <button key={item.id} className={`discovery-card${selected === item.id ? ' is-selected' : ''}`} aria-label={item.name} aria-pressed={selected === item.id} onClick={() => onSelect(selected === item.id ? undefined : item.id)}>
        <span className={`discovery-icon discovery-${item.id}`}><Icon /></span><span className="discovery-card-text"><strong>{item.name}</strong><span>{item.description}</span></span><span className="discovery-count">{item.coverage.available ? item.coverage.matched.toLocaleString('en-IN') : '—'}</span>
      </button>; })}</div>
      <div className="discovery-status"><Space size={6} wrap>{data.refreshing ? <><Spin size="small" /><span>Updating market groups… previous results remain visible</span></> : <><span className="discovery-status-dot" /><span>{data.market.open ? 'Market snapshot · updates about every 2 minutes' : `${data.market.reason} · automatic updates paused`}</span></>}{data.stale && <Tag color="orange">Older snapshot</Tag>}</Space><span>{data.sessionDate ? `Session ${date(data.sessionDate)}` : 'Market snapshot not available'}{data.capturedAt ? ` · captured ${discoveryTime(data.capturedAt)}` : ''}</span></div>
      {data.warning && <Alert showIcon type="warning" title={data.warning} />}
      {selected && !group && <Alert type="info" title="This discovery group is not available" action={<Button onClick={() => onSelect()}>Show all stocks</Button>} />}
      {group && <div className="discovery-selection"><div><Space wrap><h3>{group.name}</h3><Tag>{group.coverage.matched.toLocaleString('en-IN')} matches</Tag>{group.family === 'company' && <Tag>Saved company reports</Tag>}</Space><p>{group.rankLabel} · {group.coverage.available.toLocaleString('en-IN')} of {group.coverage.total.toLocaleString('en-IN')} listings have the required data{group.coverage.missing ? ` · ${group.coverage.missing.toLocaleString('en-IN')} excluded for missing, expired or different-session data` : ''}.</p></div><Space wrap><Button aria-label="View rules" icon={<InfoCircleOutlined />} onClick={() => setRules(group)}>View rules</Button><Button type="text" onClick={() => onSelect()}>Show all stocks</Button></Space></div>}
    </> : data && !error ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="Discovery groups unavailable" /> : null}
    <Drawer open={!!rules} onClose={() => setRules(undefined)} title={`${rules?.name ?? ''} · group rules`} size={520}>
      {rules && <div className="discovery-rules"><p>Every condition below must match (AND).</p><ol>{rules.criteria.map((rule, i) => <li key={i}><span>{rule.label}</span><strong>{rule.operator === '>=' ? '≥' : rule.operator === '<=' ? '≤' : rule.operator} {discoveryNumber(rule.value, rule.unit)}</strong></li>)}</ol><p><strong>Order:</strong> {rules.rankLabel}. All matches are shown; pagination does not change the ranking.</p>
        <h3>How the data is used</h3>
        {rules.family === 'session' ? <><p>Dhan quote snapshots across the active cash-stock universe. Change compares the snapshot price with the previous close. Each listing must have a valid trade timestamp in the displayed session. After the close, the dated NSE daily report supplies the previous-close reference because broker day-change values may reset; unverified NSE changes are excluded.</p><p>Estimated traded value = session volume × session average price (VWAP), converted to ₹ crore. This is an estimate, not an exchange-reported turnover figure.</p><p>The universe is fetched in batches. The collection window is {data?.captureStartedAt ? discoveryTime(data.captureStartedAt) : 'not available'} to {data?.capturedAt ? discoveryTime(data.capturedAt) : 'not available'}. Visible prices can move after the group was ranked.</p></> : <><p>Latest valid saved company data from Dhan company information, with Dhan public annual financial data used where available for ROE. Expired or missing values do not pass. Use “Why included” to see each stock’s figures, reporting period and source.</p><p>Company data refreshes through the app’s data imports. Refreshing groups rechecks saved reports; it does not download thousands of company reports.</p>{rules.id === 'quality' && <p>ROE and debt ratios can refer to different reporting periods. Financial companies are not excluded; debt/equity needs sector-specific interpretation.</p>}<p>These market-cap ranges are discovery filters, not official large/mid/small-cap index classifications.</p></>}
        <h3>Scope & coverage</h3><p>The exchange selector applies to every group. With both exchanges selected, a company listed on NSE and BSE can appear twice. Search narrows this group, while “Show all stocks” removes the group filter.</p><p>{rules.coverage.available.toLocaleString('en-IN')} of {rules.coverage.total.toLocaleString('en-IN')} active listings can be evaluated. Missing required data is excluded, never treated as zero.</p><p className="muted">Discovery helps you research. A match is not a buy/sell signal, monthly qualification or an order. Star a stock, open its chart, or manually add it to qualification using your own reason.</p></div>}
    </Drawer>
  </section>;
}
