import { z } from 'zod';
export const calculationSettingsSchema = z.object({
  streakPeriod: z.number().int().min(1).max(500).optional(),
  rankPeriod: z.number().int().min(1).max(500).optional(),
  deviation: z.enum(['sample','population']).optional(),
  source: z.enum(["close", "open", "high", "low", "hl2", "hlc3", "ohlc4"]).optional(),
  maType: z.enum(["sma", "ema", "wma", "vwma", "hma", "dema"]).optional(),
  multiplier: z.number().finite().min(0.1).max(20).optional(),
  anchor: z.enum(["session", "week", "month", "custom"]).optional(),
  anchorDate: z.string().max(40).optional(),
  anchorTime: z.string().max(40).optional(),
  start: z.number().finite().min(0.001).max(1).optional(),
  increment: z.number().finite().min(0.001).max(1).optional(),
  maximum: z.number().finite().min(0.001).max(1).optional(),
  conversionPeriod: z.number().finite().min(1).max(500).int().optional(),
  basePeriod: z.number().finite().min(1).max(500).int().optional(),
  spanPeriod: z.number().finite().min(1).max(500).int().optional(),
  displacement: z.number().finite().min(0).max(120).int().optional(),
  atrPeriod: z.number().finite().min(1).max(500).int().optional(),
  pivotType: z.enum(["traditional", "fibonacci", "camarilla"]).optional(),
  pivotFrame: z.enum(["1d", "1w", "1mo"]).optional(),
  overbought: z.number().finite().min(1).max(100).int().optional(),
  oversold: z.number().finite().min(0).max(99).int().optional(),
  fastPeriod: z.number().finite().min(2).max(500).int().optional(),
  slowPeriod: z.number().finite().min(3).max(500).int().optional(),
  signalPeriod: z.number().finite().min(1).max(100).int().optional(),
  smoothK: z.number().finite().min(1).max(100).int().optional(),
  dPeriod: z.number().finite().min(1).max(100).int().optional(),
  stochPeriod: z.number().finite().min(1).max(500).int().optional(),
  adxSmoothing: z.number().finite().min(1).max(500).int().optional(),
  maPeriod: z.number().finite().min(0).max(500).int().optional(),
  benchmark: z.enum(["NIFTY 50", "NIFTY BANK", "SENSEX", "NIFTY IT", "NIFTY AUTO", "NIFTY FMCG", "NIFTY PHARMA", "NIFTY METAL", "NIFTY REALTY", "NIFTY ENERGY", "NIFTY FIN SERVICE", "NIFTY PSU BANK", "NIFTY PVT BANK", "NIFTY HEALTHCARE"]).optional(),
}).strict();
