import { expect, test, type Page } from '@playwright/test';
import { signInAdmin } from './helpers/auth';
import { readFile } from 'node:fs/promises';
import { backtestSchema, defaultBacktestConfig } from '../src/modules/backtesting/schemas/backtestSchema';
import { createBacktestScope, simulateBacktest } from '../src/modules/backtesting/api/mockBacktest';
import { defaultExitRule } from '../src/modules/backtesting/config/backtestDefaults';
import { initialTemplates } from '../src/modules/qualification/config/templates';
import type { BacktestRun } from '../src/modules/backtesting/types';

const entry = initialTemplates.find((rule) => rule.id === 'tactical-intraday')!;
const runs = (page: Page): Promise<BacktestRun[]> => page.evaluate(() => JSON.parse(localStorage.getItem('quantforge-backtests')!).state.workspaces['admin@example.com'].runs);
const choose = async (page: Page, label: string, option: string) => { await page.getByRole('combobox', { name: label, exact: true }).click(); await page.locator('.ant-select-dropdown:visible .ant-select-item-option').filter({ hasText: new RegExp(`^${option}$`) }).click(); };

test('configuration rejects incoherent dates and daily same-day exits; simulated accounting reconciles', () => {
  const config = { ...defaultBacktestConfig(entry.id, defaultExitRule.id), startDate: '2026-08-03', endDate: '2026-08-31' };
  expect(backtestSchema.safeParse({ ...config, timeframe: '1d', overnight: false }).success).toBe(false);
  expect(backtestSchema.safeParse({ ...config, endDate: '2026-07-01' }).success).toBe(false);
  expect(backtestSchema.safeParse({ ...config, startDate: '2026-02-30' }).success).toBe(false);
  expect(backtestSchema.safeParse({ ...config, initialCapital: 0 }).success).toBe(false);
  expect(backtestSchema.safeParse({ ...config, slippagePercent: -1 }).success).toBe(false);
  expect(createBacktestScope({ ...config, universe: 'current' }).symbols).toHaveLength(0);
  const scope = createBacktestScope(config);
  const run: BacktestRun = { id: 'fixture', createdAt: 0, status: 'running', entryRule: entry, exitRule: defaultExitRule, config, scope };
  const result = simulateBacktest(run);
  expect(result.trades.length).toBeGreaterThan(0);
  expect(result.trades.some((trade) => trade.pnl < 0)).toBe(true);
  expect(result.trades.some((trade) => trade.pnl > 0)).toBe(true);
  expect(result.endingCapital).toBeCloseTo(config.initialCapital + result.trades.reduce((sum, trade) => sum + trade.pnl, 0), 6);
  expect(result.fees).toBeCloseTo(result.trades.reduce((sum, trade) => sum + trade.fees, 0), 6);
  for (const trade of result.trades) {
    expect(trade.quantity).toBeGreaterThan(0);
    expect(trade.exitTime).toBeGreaterThan(trade.entryTime);
    expect(trade.pnl).toBeCloseTo((trade.exit - trade.entry) * trade.quantity - trade.fees, 6);
    expect(trade.fees).toBeGreaterThan(0);
    expect(scope.symbols.some((stock) => stock.symbol === trade.symbol)).toBe(true);
  }
  const expensive = simulateBacktest({ ...run, config: { ...config, slippagePercent: 1, feePercent: 1 } });
  expect(expensive.netPnl).toBeLessThan(result.netPnl);
});

test('backtests queue, cancel, pin settings, export and persist; paper overrides do not alter the report', async ({ page }) => {
  test.setTimeout(90000);
  await page.clock.install({ time: new Date('2026-09-22T06:00:00Z') });
  await signInAdmin(page);
  await page.getByRole('link', { name: 'Algo Strategies', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Save strategy', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Backtest strategy', exact: true }).click();
  await expect(page).toHaveURL(/strategies\?tab=backtests&strategy=tactical-intraday/);
  await expect(page.getByLabel('Initial capital (₹)', { exact: true })).toHaveValue('100000');
  await page.getByRole('button', { name: 'Save setup', exact: true }).click();
  expect(await runs(page)).toEqual([]);
  await choose(page, 'Execution interval', 'Daily');
  await page.getByRole('button', { name: 'Run backtest', exact: true }).click();
  await expect(page.getByText('Daily candles require overnight holding.', { exact: false })).toBeVisible();
  expect(await runs(page)).toEqual([]);
  await choose(page, 'Execution interval', '15 minutes');
  await page.getByRole('button', { name: 'Run backtest', exact: true }).click();
  await expect(page.locator('.bt-progress')).toContainText('Queued');
  await expect(page.getByRole('region', { name: 'Backtest result' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Cancel run' }).click();
  expect((await runs(page))[0].status).toBe('cancelled');
  await page.getByRole('button', { name: 'Run backtest', exact: true }).click();
  await page.getByLabel('Initial capital (₹)', { exact: true }).fill('200000');
  await page.clock.fastForward(31000);
  await expect(page.getByRole('region', { name: 'Backtest result' })).toBeVisible();
  await expect(page.getByText("Showing the previous setup's result")).toBeVisible();
  const report = (await runs(page))[0];
  expect(report.config.initialCapital).toBe(100000);
  expect(report.status).toBe('completed');
  await expect(page.getByRole('figure', { name: 'Equity curve from simulated trades' }).locator('.recharts-area-curve')).toBeVisible();
  await page.getByRole('tab', { name: /Trade ledger/ }).click();
  await expect(page.locator('.bt-trades-table tbody tr.ant-table-row')).toHaveCount(8);
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export trades' }).click();
  const csv = await readFile((await (await downloadEvent).path())!, 'utf8');
  expect(csv).toContain('Simulated, not historical performance');
  expect(csv.trim().split('\r\n')).toHaveLength(report.result!.trades.length + 1);
  await page.getByRole('button', { name: 'Start paper session' }).click();
  await expect(page).toHaveURL(/paper-trading\?session=/);
  await page.getByRole('button', { name: 'Manual buy', exact: true }).click();
  await choose(page, 'Qualified stock', 'RELIANCE');
  await page.getByLabel('Quantity', { exact: true }).fill('999999');
  await page.getByRole('button', { name: 'Confirm paper buy' }).click();
  await expect(page.getByRole('dialog')).toContainText('Quantity exceeds');
  await page.getByLabel('Quantity', { exact: true }).fill('2');
  await page.getByLabel('Reason (optional)', { exact: true }).fill('Manual review of setup');
  await page.getByRole('button', { name: 'Confirm paper buy' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.locator('.paper-positions')).toContainText('Manual entry');
  await page.getByRole('button', { name: 'Sell RELIANCE now' }).click();
  await expect(page.getByRole('switch', { name: 'Allow new algo entries' })).not.toBeChecked();
  await expect(page.locator('.paper-positions tbody tr.ant-table-row')).toHaveCount(0);
  await page.getByRole('tab', { name: /Activity/ }).click();
  await expect(page.getByRole('tabpanel')).toContainText('Manual sell override');
  await page.getByRole('switch', { name: 'Allow new algo entries' }).click();
  await page.getByRole('button', { name: 'Open signal runner', exact: true }).click();
  await page.getByRole('button', { name: 'Start monitoring', exact: true }).click();
  await page.clock.fastForward(4000);
  await page.getByRole('button', { name: 'Paper trading', exact: true }).click();
  await page.getByRole('tab', { name: 'Strategy alerts', exact: true }).click();
  await page.getByRole('button', { name: 'Review paper buy', exact: true }).first().click();
  await page.getByLabel('Quantity', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Confirm paper buy', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('tab', { name: /Open positions/ }).click();
  await expect(page.locator('.paper-positions')).toContainText('Signal entry');
  await page.getByRole('button', { name: 'Sell all & pause', exact: true }).click();
  await page.locator('.ant-popconfirm').getByRole('button', { name: 'Sell all & pause', exact: true }).click();
  await expect(page.locator('.paper-positions tbody tr.ant-table-row')).toHaveCount(0);
  expect((await runs(page))[0]).toEqual(report);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Paper trading', exact: true })).toBeVisible();
  await expect(page.getByRole('switch', { name: 'Allow new algo entries' })).not.toBeChecked();
  const storedPaper = await page.evaluate(() => JSON.parse(localStorage.getItem('quantforge-paper-sessions')!).state.sessions['admin@example.com'][0]);
  expect(storedPaper.events).toHaveLength(4);
  expect(storedPaper.cash).toBeCloseTo(100000 + storedPaper.realized, 6);
});

test('exit rules connect to Algo Strategies; workbench, report and paper layouts support themes and mobile', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.clock.install({ time: new Date('2026-09-22T06:00:00Z') });
  await signInAdmin(page);
  await page.getByRole('link', { name: 'Algo Strategies', exact: true }).click();
  await page.getByRole('tab', { name: 'Backtests', exact: true }).click();
  await page.getByRole('button', { name: 'Edit exit conditions' }).click();
  await page.getByRole('tab', { name: /Sell rules/ }).click();
  await page.getByLabel('Threshold (RSI)', { exact: true }).fill('40');
  await page.getByRole('button', { name: 'Save strategy', exact: true }).click();
  const exit = await page.evaluate(() => JSON.parse(localStorage.getItem('quantforge-qualification')!).state.workspaces['admin@example.com'].templates.find((rule: { name: string }) => rule.name === 'Intraday Momentum · Sell'));
  expect(exit.side).toBe('SELL');
  await page.getByRole('button', { name: 'Backtest strategy', exact: true }).click();
  await choose(page, 'Stock universe', 'Current qualified list · exploratory');
  await expect(page.getByText('Current selection applied to past dates', { exact: true })).toBeVisible();
  await choose(page, 'Stock universe', 'Demo monthly snapshots');
  await page.getByRole('button', { name: 'Run backtest', exact: true }).click();
  await page.clock.fastForward(31000);
  await expect(page.getByRole('region', { name: 'Backtest result' })).toBeVisible();
  for (const theme of ['light', 'dark'] as const) {
    await page.emulateMedia({ colorScheme: theme });
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme);
    await page.evaluate(() => window.scrollTo(0, 0));
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: `test-results/screenshots/backtesting-${theme}.png`, fullPage: true, animations: 'disabled' });
  }
  await page.getByRole('tab', { name: /Run history/ }).click();
  await expect(page.getByRole('button', { name: 'View report' })).toBeVisible();
  await page.getByRole('button', { name: 'View report' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ colorScheme: 'light' });
  await expect(page.getByRole('button', { name: 'Jump to report' })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollHeight)).toBeGreaterThan(2000);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/screenshots/backtesting-mobile.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Start paper session' }).click();
  await expect(page.getByRole('heading', { name: 'Paper trading', exact: true })).toBeVisible();
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/screenshots/paper-trading-mobile.png', fullPage: true, animations: 'disabled' });
  expect(errors).toEqual([]);
});
