import { test, expect, type Page } from '@playwright/test';
import { initialMonthlyRule, newMonthlyCondition } from '../src/modules/qualification/config/monthlyFields';
import { ruleFields } from '../src/modules/qualification/config/ruleFields';
import { reviewMonthlyRule } from '../../backend/src/modules/qualification/services/monthly-review.service';
const now = '2026-09-30T12:00:00Z';
const stock = { instrumentId:'NSE:1', isin:'INE123', source:'scan', addedAt:now, instrument:{symbol:'EXAMPLE',name:'Example Limited',exchange:'NSE'}, metrics:{sector:'Banking',index:[]} };
const bars = Array.from({length:240},(_,i)=>({time:new Date(Date.UTC(2026,0,i+1)).toISOString().slice(0,10),open:100+i*.2,high:105+i*.2,low:97+i*.2,close:102+i*.2+Math.sin(i),volume:1000+i*5}));
async function fixture(page:Page) {
  await page.clock.setFixedTime(new Date(now));
  await page.addInitScript(()=> {window.EventSource=class {onmessage=null;onerror=null;close(){}} as unknown as typeof EventSource;});
  let rule={...initialMonthlyRule,groups:[{logic:'AND' as const,conditions:[{...newMonthlyCondition('marketCap'),value:2000},{...newMonthlyCondition('ema'),period:5,operand:'field' as const,compareField:'ema',comparePeriod:21}]}]},revision=1;
  const writes:Record<string,unknown>[]=[];
  await page.route(url=>url.pathname.startsWith('/api/'),route=>route.fulfill({json:route.request().url().endsWith('/session')?{authenticated:true,mode:'local'}:{}}));
  await page.route('**/api/qualification',route=>route.fulfill({json:{month:'2026-09',rule:{rule,revision,fingerprint:'test'},runs:[],universe:{runId:'test',members:[stock]},canRun:false}}));
  await page.route('**/api/qualification/universe',route=>route.fulfill({json:[stock]}));
  await page.route('**/api/qualification/membership',route=>route.fulfill({json:{month:'2026-09',published:true,members:[stock]}}));
  await page.route('**/api/qualification/rule/review',route=>route.fulfill({json:reviewMonthlyRule(route.request().postDataJSON())}));
  await page.route('**/api/qualification/rule',route=>{const body=route.request().postDataJSON();writes.push(body);rule=body.rule;revision++;return route.fulfill({json:{revision}});});
  await page.route('**/api/market-data/capabilities',route=>route.fulfill({json:{monthlyFields:Object.keys(ruleFields).filter(id=>ruleFields[id].monthly),technical:Object.keys(ruleFields).filter(id=>ruleFields[id].source==='candles'),snapshotFields:[],choices:{sector:[],index:[]}}}));
  await page.route('**/api/watchlists',route=>route.fulfill({json:{lists:[{_id:'personal',ids:[]}],universeCount:1}}));
  await page.route('**/api/stocks/**',route=>{
    const url=new URL(route.request().url()),instrument={_id:stock.instrumentId,...stock.instrument,isin:stock.isin,active:true};
    if(url.pathname.endsWith('/quotes'))return route.fulfill({json:{quotes:[]}});
    if(url.pathname.endsWith('/listings'))return route.fulfill({json:{instrument,listings:[instrument]}});
    if(url.pathname.endsWith('/chart'))return route.fulfill({json:{instrumentId:stock.instrumentId,timeframe:url.searchParams.get('timeframe'),bars: url.pathname.includes('/benchmarks/')?bars.map(b=>({...b,close:100})):bars,source:'fixture',historyVerified:true,latestCandleAt:bars.at(-1)!.time}});
    return route.fulfill({json:{instrument,facts:[],qualification:null}});
  });
  return writes;
}

test('monthly summaries edit settings, review simplification and save without running',async({page},info)=>{
  test.setTimeout(60000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  const writes=await fixture(page);await page.goto('/qualification?tab=rules');
  await expect(page.getByRole('button',{name:'Save rule',exact:true})).toBeDisabled({timeout:20000});
  await expect(page.getByLabel('Monthly rule review')).toContainText('No conflict found');
  await page.getByRole('button',{name:'Edit monthly condition 1',exact:true}).click();
  const first=page.getByLabel('Monthly condition 1 in group 1',{exact:true});
  await first.getByRole('spinbutton').fill('');
  await expect(page.locator('.monthly-condition-footer')).toContainText('Enter value');
  await first.getByRole('spinbutton').fill('2000');
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.getByRole('button',{name:'Edit monthly condition 2',exact:true}).click();
  const row=page.getByLabel('Monthly condition 2 in group 1', {exact:true});
  await row.getByText('Indicator settings',{exact:true}).first().click();
  await row.getByLabel('Price source').first().click();
  await page.getByRole('option',{name:'OPEN',exact:true}).click();
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await expect(row).toContainText('Price source: open');
  await page.getByRole('button',{name:'Add condition',exact:true}).click();
  await page.getByRole('button',{name:'Done',exact:true}).click();
  const review=page.getByLabel('Monthly rule review');
  await expect(review.getByText('Simplify',{exact:true})).toBeVisible();
  await review.locator('.ant-collapse-header').first().click();
  await page.getByRole('button',{name:'Preview simplification'}).click();
  await page.getByRole('button',{name:'Apply to draft',exact:true}).click();
  await expect(page.locator('.monthly-condition-summary')).toHaveCount(2);
  await page.getByRole('button',{name:'Save rule',exact:true}).click();
  await expect(page.getByRole('button',{name:/Save rule$/})).toBeDisabled();
  await expect(page.locator('.monthly-save-actions .ant-btn-loading')).toHaveCount(0,{timeout:15000});
  expect(writes).toHaveLength(1);
  const saved=writes[0].rule as typeof initialMonthlyRule;
  expect(saved.groups[0].conditions.find(c=>c.field==='ema')?.settings).toEqual({source:'open'});
  expect(saved.groups[0].conditions.every(c=>c.timeframe==='1mo')).toBe(true);
  await expect(page.getByLabel('Monthly rule review')).toContainText('No conflict found');
  const layout = await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,x:scrollX,main:document.querySelector('main')!.getBoundingClientRect().x}));
  expect(layout.scroll,JSON.stringify(layout)).toBeLessThanOrEqual(layout.width+1);
  expect(layout.main,JSON.stringify(layout)).toBeGreaterThanOrEqual(228);
  await page.evaluate(()=>scrollTo(0,0));
  const bounds=await page.evaluate(()=>['.app-content','main','.qualification-page','.q-workspace','.monthly-rule-builder'].map(sel=>{const e=document.querySelector(sel)!;const b=e.getBoundingClientRect();return {sel,x:b.x,width:b.width,scrollLeft:e.scrollLeft,scrollWidth:e.scrollWidth,overflow:getComputedStyle(e).overflow};}));
  await info.attach('layout.json',{body:JSON.stringify(bounds),contentType:'application/json'});
  await page.screenshot({path:info.outputPath('monthly-viewport.png'),animations:'disabled'});
  await page.screenshot({path:info.outputPath('monthly-desktop.png'),fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Edit monthly condition 1',exact:true}).click();
  expect(await page.locator('.monthly-rule-builder').first().evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);
  await page.screenshot({path:info.outputPath('monthly-mobile.png'),fullPage:true});
  expect(errors).toEqual([]);
});

test('new overlays and study panels render, configured values persist, benchmark history is requested',async({page},info)=>{
  const errors:string[]=[],benchmarks:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/stocks/benchmarks/'))benchmarks.push(r.url());});
  await fixture(page);
  await page.addInitScript(()=>!localStorage.getItem('quantforge-chart-preferences')&&localStorage.setItem('quantforge-chart-preferences',JSON.stringify({version:1,state:{research:{kind:'candles',showVolume:true,timeframe:'1d',custom:[{id:'cloud',kind:'ichimoku',period:14,timeframe:'chart',color:'#8064d8'},{id:'wma',kind:'wma',period:20,timeframe:'chart',color:'#4076d9'},{id:'cmf',kind:'cmf',period:20,timeframe:'chart',color:'#168b8b'},{id:'rs',kind:'relativeStrength',period:20,benchmark:'SENSEX',timeframe:'1d',color:'#c58822'}]},strategy:{kind:'candles',custom:[]},layouts:[]}})));
  await page.goto('/qualification');await page.getByRole('button',{name:'View EXAMPLE details'}).click();await page.getByRole('tab',{name:'Advanced chart',exact:true}).click();
  const drawer=page.getByRole('dialog');
  await expect(drawer.getByLabel('Visible indicators')).toContainText('vs SENSEX');
  await expect(drawer.getByLabel('Visible indicators')).not.toContainText('Waiting for matching');
  expect(benchmarks.length).toBeGreaterThan(0);
  await expect(drawer.getByRole('figure')).toBeVisible();
  await drawer.getByRole('button',{name:'Indicators',exact:true}).click();await page.getByRole('button',{name:'Edit WMA 20'}).click();
  const modal=page.getByRole('dialog',{name:'WMA settings'});
  await modal.getByLabel('Price source').click();await page.getByRole('option',{name:'OPEN',exact:true}).click();await modal.getByRole('button',{name:'Apply indicator settings'}).click();
  await drawer.getByRole('heading',{name:'Price & volume'}).click();
  await expect(drawer.getByLabel('Visible indicators')).toContainText('WMA 20 · 1d · OPEN');
  await page.screenshot({path:info.outputPath('indicators-desktop.png')});
  await page.reload();await page.getByRole('button',{name:'View EXAMPLE details'}).click();await page.getByRole('tab',{name:'Advanced chart',exact:true}).click();
  await expect(page.getByLabel('Visible indicators')).toContainText('WMA 20 · 1d · OPEN');
  expect(errors).toEqual([]);
});

test('discover and configure new indicators, crossover presets, favourites and unified volume',async({page},info)=>{
  test.setTimeout(60000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  const writes=await fixture(page);
  await page.goto('/qualification');await page.getByRole('button',{name:'View EXAMPLE details'}).click();await page.getByRole('tab',{name:'Advanced chart',exact:true}).click();
  const drawer=page.locator('.stock-detail-drawer');
  const open=()=>drawer.getByRole('button',{name:'Indicators',exact:true}).click();
  await open();
  const search=page.getByLabel('Indicator type');
  await search.fill('double exponential');
  await page.getByRole('option',{name:'Double EMA (DEMA)',exact:true}).click();
  await page.getByRole('button',{name:'Save favourite',exact:true}).click();
  await page.getByRole('button',{name:'Configure indicator',exact:true}).click();
  const dema=page.getByRole('dialog',{name:'Double EMA (DEMA) settings'});
  await dema.getByLabel('Period (candles)').fill('9');await dema.getByRole('button',{name:'Add to chart'}).click();
  await expect(drawer.getByLabel('Visible indicators')).toContainText('Double EMA (DEMA) 9');
  await open();await search.fill('crsi');await page.getByRole('option',{name:'Connors RSI (CRSI)',exact:true}).click();
  await page.getByRole('button',{name:'Configure indicator',exact:true}).click();
  const crsi=page.getByRole('dialog',{name:'Connors RSI (CRSI) settings'});await crsi.getByLabel('Return rank lookback').fill('20');await crsi.getByRole('button',{name:'Add to chart'}).click();
  await expect(drawer.getByLabel('Visible indicators')).toContainText('Connors RSI (CRSI) 3/2/20');
  await open();await search.fill('golden');await page.getByRole('option',{name:'Golden Cross (50 / 200)',exact:true}).click();
  await page.getByRole('button',{name:'Configure indicator',exact:true}).click();
  const cross=page.getByRole('dialog',{name:'Moving Average Cross settings'});
  await expect(cross.getByLabel('Fast period')).toHaveValue('50');await expect(cross.getByLabel('Slow period')).toHaveValue('200');
  await cross.getByLabel('Fast period').fill('3');await cross.getByLabel('Slow period').fill('8');
  await cross.getByRole('checkbox',{name:'Fast MA',exact:true}).uncheck();await cross.getByLabel('Slow MA colour').fill('#123456');
  await cross.getByRole('button',{name:'Add to chart'}).click();
  await expect(drawer.getByRole('figure')).not.toHaveAttribute('data-cross-count','0');
  await expect(drawer.getByLabel('Visible indicators')).toContainText('SMA 3/8');
  await open();await page.getByRole('button',{name:'Edit Volume',exact:true}).click();
  const volume=page.getByRole('dialog',{name:'Volume settings'});
  await volume.getByRole('checkbox',{name:'Show volume moving average',exact:true}).check();await volume.getByLabel('Volume MA period').fill('12');await volume.getByLabel('Bar opacity (%)').fill('65');
  await volume.getByRole('button',{name:'Apply volume settings'}).click();
  await expect(drawer.getByLabel('Visible indicators')).toContainText('Volume SMA 12');
  await open();await page.getByRole('button',{name:'Hide Volume',exact:true}).click();
  await expect(drawer.getByRole('checkbox',{name:'Volume',exact:true})).not.toBeChecked();
  await expect(drawer.getByRole('figure')).toHaveAttribute('data-volume-visible','false');
  await drawer.getByRole('heading',{name:'Price & volume'}).click();await drawer.getByRole('checkbox',{name:'Volume',exact:true}).check();
  await page.reload();await page.getByRole('button',{name:'View EXAMPLE details'}).click();await page.getByRole('tab',{name:'Advanced chart',exact:true}).click();
  await expect(drawer.getByLabel('Visible indicators')).toContainText('Volume SMA 12');
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('quantforge-chart-preferences')!).state);
  expect(stored.favourites).toContain('dema');expect(stored.research.volumeStyle.opacity).toBe(65);
  expect(stored.research.custom.find((i:{kind:string})=>i.kind==='maCross').lineStyles['0'].visible).toBe(false);
  await page.screenshot({path:info.outputPath('expanded-indicators.png'),animations:'disabled'});
  await page.setViewportSize({width:390,height:844});await open();await page.getByRole('button',{name:'Edit Volume',exact:true}).click();
  expect(await volume.evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);
  await expect.poll(()=>volume.evaluate(e=>getComputedStyle(e).transform)).toBe('none');
  await page.screenshot({path:info.outputPath('volume-settings-mobile.png'),animations:'disabled'});
  expect(writes).toHaveLength(0);expect(errors).toEqual([]);
});
