import { expect, test, type Page } from '@playwright/test';
import { signInAdmin } from './helpers/auth';
import { createQualificationWorkspace } from '../src/modules/qualification/api/mockQualification';
import { evaluateMonitor, samplePositions } from '../src/modules/signals/api/mockMonitor';
import { closedCandle, demoSessionTime, monitorDefinitions, nextCandle, sessionBounds } from '../src/modules/signals/utils/monitoring';
import type { MonitorWorkspace, StrategyMonitor } from '../src/modules/signals/types/monitor';
import { defaultBacktestConfig } from '../src/modules/backtesting/schemas/backtestSchema';
import type { PaperSession } from '../src/modules/paper-trading/types';

const snapshot = (page: Page): Promise<MonitorWorkspace> => page.evaluate(() => JSON.parse(localStorage.getItem('quantforge-signal-monitor')!).state.workspaces['admin@example.com']);

test('candle timing aligns to the exchange session and excludes incomplete higher timeframes', () => {
  const time = demoSessionTime(Date.parse('2026-09-22T06:00:00Z'));
  const { start, end } = sessionBounds(time);
  expect(closedCandle(start, '5m')).toBeUndefined();
  expect(closedCandle(start + 299999, '5m')).toBeUndefined();
  expect(closedCandle(start + 300000, '5m')).toBe(start + 300000);
  expect(closedCandle(time + 120000, '15m')).toBe(time);
  expect(nextCandle(time, '5m')).toBe(time + 300000);
  expect(closedCandle(time, 'daily')).toBeUndefined();
  expect(nextCandle(time, 'daily')).toBe(end);
  expect(closedCandle(end, 'daily')).toBe(end);
  expect(nextCandle(end, '5m')).toBeUndefined();
});

test('entry checks stay inside the cache; held exits survive pausing, rule edits and universe removal', () => {
  const qualification = createQualificationWorkspace('2026-09');
  const cache = qualification.caches['2026-09'];
  const definition = structuredClone(monitorDefinitions(qualification)[0]);
  const condition = { ...definition.entry.groups[0].conditions[0], left: 'close' as const, operator: 'gt' as const, rightType: 'value' as const, value: 0 };
  definition.entry.groups = [{ logic: 'AND', conditions: [condition] }];
  definition.exit = { ...structuredClone(definition.entry), id: 'paired-exit', side: 'SELL' };
  const clock = demoSessionTime(Date.parse('2026-09-22T06:00:00Z')) + 1000;
  const monitor: StrategyMonitor = { definition, state: 'monitoring', readyAt: 0, entryPaused: true, checkedCount: 0, lastExitBars: {}, lastProtection: {}, samplePositions: samplePositions(definition, cache) };
  const workspace: MonitorWorkspace = { clock, lastTick: clock, feed: 'healthy', monitors: { [definition.id]: monitor }, signals: [], interrupted: false };
  const input = { workspace, definition, cache, sessions: [], globalPaused: true, manual: false };
  const result = evaluateMonitor(monitor, input);
  const buys = result.signals.filter(event => event.side === 'BUY');
  const sells = result.signals.filter(event => event.side === 'SELL');
  expect(result.monitor.checkedCount).toBe(62);
  expect(buys).toHaveLength(62);
  expect(buys.every(event => event.disposition === 'blocked' && cache.candidates.some(stock => stock.symbol === event.symbol))).toBe(true);
  expect(sells).toHaveLength(2);
  expect(sells.every(event => event.disposition === 'ready')).toBe(true);
  expect(sells.some(event => event.outsideUniverse)).toBe(true);
  expect(evaluateMonitor(result.monitor, { ...input, workspace: { ...workspace, signals: result.signals }, manual: true }).signals).toHaveLength(0);
  expect(evaluateMonitor(monitor, { ...input, workspace: { ...workspace, feed: 'disconnected' } }).signals).toHaveLength(0);
  const changed = structuredClone(definition); changed.entry.revision++;
  const revised = evaluateMonitor({ ...monitor, entryPaused: false }, { ...input, definition: changed, globalPaused: false });
  expect(revised.signals.filter(event => event.side === 'BUY').every(event => event.explanation.includes('Saved rules changed'))).toBe(true);
  expect(revised.signals.filter(event => event.side === 'SELL')).toHaveLength(2);
  const noPool = evaluateMonitor(monitor, { ...input, cache: { ...cache, candidates: [] } });
  expect(noPool.signals).toHaveLength(2);
  expect(noPool.signals.every(event => event.side === 'SELL' && event.outsideUniverse)).toBe(true);
  const heldGuard = evaluateMonitor({ ...monitor, entryPaused: false }, { ...input, globalPaused: false });
  expect(heldGuard.signals.find(event => event.side === 'BUY' && event.symbol === monitor.samplePositions[0].symbol)?.explanation).toContain('Already held');
  const close = evaluateMonitor(monitor, { ...input, workspace: { ...workspace, clock: sessionBounds(clock).end - 15 * 60000 } });
  expect(close.signals.filter(event => event.side === 'SELL').every(event => event.trigger === 'Session exit')).toBe(true);
  expect(close.signals.filter(event => event.side === 'BUY').every(event => event.explanation.includes('entry window closed'))).toBe(true);
  const outside = monitor.samplePositions[1];
  const paper: PaperSession = { id: 'paper-held', runId: 'report', name: 'Manual override', createdAt: clock, config: defaultBacktestConfig(definition.entry.id, definition.exit.id), entryRule: definition.entry, exitRule: definition.exit, scope: { mode: 'current', label: 'Earlier list', manualCount: 0, symbols: [{ symbol: outside.symbol, price: outside.price, manual: false }] }, cash: 90000, realized: 0, paused: true, tick: 0, events: [], positions: [{ id: 'position', symbol: outside.symbol, quantity: 1, entry: outside.price, entryFee: 0, stop: outside.stop, target: outside.target, source: 'Manual', openedAt: clock }] };
  const manual = evaluateMonitor({ ...monitor, entryPaused: false, samplePositions: [] }, { ...input, globalPaused: false, sessions: [paper] });
  expect(manual.signals.filter(event => event.side === 'BUY').every(event => event.disposition === 'blocked' && event.explanation.includes('manual override'))).toBe(true);
  expect(manual.signals.find(event => event.side === 'SELL')).toMatchObject({ outsideUniverse: true, disposition: 'ready', positionId: 'paper-held:position' });
  expect(paper.positions).toHaveLength(1);
  expect(paper.events).toHaveLength(0);
});

test('monitoring warms up, deduplicates candles, expires alerts and requires restart after reload', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-22T06:00:00Z') });
  await signInAdmin(page);
  await page.getByRole('link', { name: 'Signal Runner', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Advance demo candle' })).toBeDisabled();
  await page.getByRole('button', { name: 'Start monitoring', exact: true }).click();
  await expect(page.getByText('Loading sample history', { exact: true })).toBeVisible();
  await page.clock.fastForward(4000);
  await expect(page.getByText('Monitoring', { exact: true }).first()).toBeVisible();
  const started = await snapshot(page);
  expect(started.monitors['tactical-intraday'].checkedCount).toBe(62);
  expect(started.signals.length).toBeGreaterThan(0);
  await page.getByRole('button', { name: 'Check latest candles' }).click();
  expect((await snapshot(page)).signals).toHaveLength(started.signals.length);
  await page.clock.runFor(31000);
  expect((await snapshot(page)).signals.every(event => event.disposition === 'expired')).toBe(true);
  await page.getByRole('button', { name: 'Advance demo candle' }).click();
  const advanced = await snapshot(page);
  expect(advanced.signals.filter(event => event.disposition === 'ready').length).toBeGreaterThan(0);
  await page.reload();
  await expect(page.getByText('Previous demo monitoring stopped when the session ended.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start monitoring', exact: true })).toBeEnabled();
  expect((await snapshot(page)).signals.filter(event => event.disposition === 'ready')).toHaveLength(0);
  await page.evaluate(() => {
    const saved = JSON.parse(localStorage.getItem('quantforge-signal-monitor')!);
    saved.state.workspaces['admin@example.com'].clock -= 86400000;
    localStorage.setItem('quantforge-signal-monitor', JSON.stringify(saved));
  });
  await page.reload();
  await expect(page.getByRole('button', { name: 'Start monitoring', exact: true })).toBeEnabled();
  expect((await snapshot(page)).clock).toBe(demoSessionTime(Date.parse('2026-09-22T06:00:00Z')));
});

test('paired monitor keeps exits, blocks stale feeds and supports light, dark and mobile views', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.clock.install({ time: new Date('2026-09-22T06:00:00Z') });
  await signInAdmin(page);
  await page.getByRole('link', { name: 'Algo Strategies', exact: true }).click();
  await page.getByRole('tab', { name: /Sell rules/ }).click();
  await page.getByLabel('Threshold (RSI)', { exact: true }).fill('100');
  await page.getByRole('button', { name: 'Save strategy', exact: true }).click();
  await page.getByRole('link', { name: 'Signal Runner', exact: true }).click();
  await page.getByRole('button', { name: 'Demo controls' }).click();
  await page.getByRole('switch', { name: 'Include sample held positions' }).click();
  await page.getByRole('button', { name: 'Demo controls' }).click();
  await page.getByRole('button', { name: 'Start monitoring', exact: true }).click();
  await page.clock.fastForward(4000);
  await expect(page.getByRole('button', { name: 'Stop monitoring', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Pause new entries', exact: true }).click();
  await page.getByRole('button', { name: 'Advance demo candle' }).click();
  const paused = await snapshot(page);
  const newest = paused.signals.filter(event => event.time === paused.clock);
  expect(newest.some(event => event.side === 'SELL' && event.outsideUniverse && event.disposition === 'ready')).toBe(true);
  expect(newest.filter(event => event.side === 'BUY').every(event => event.disposition === 'blocked')).toBe(true);
  await page.getByRole('tab', { name: 'Stock coverage' }).click();
  await page.getByRole('combobox', { name: 'Coverage scope' }).click();
  await page.locator('.ant-select-dropdown:visible').getByText('Outside monthly list', { exact: true }).click();
  await expect(page.getByText('Exit only', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: /Signal activity/ }).click();
  await page.getByRole('button', { name: 'Demo controls' }).click();
  await page.getByRole('combobox', { name: 'Sample feed scenario' }).click();
  await page.locator('.ant-select-dropdown:visible').getByText('Disconnected', { exact: true }).click();
  await page.getByRole('button', { name: 'Demo controls' }).click();
  await expect(page.getByText('Feed disconnected', { exact: true })).toBeVisible();
  expect((await snapshot(page)).signals.filter(event => event.disposition === 'ready')).toHaveLength(0);
  await expect(page.getByRole('button', { name: 'Check latest candles' })).toBeDisabled();
  await page.getByRole('button', { name: 'Advance demo candle' }).click();
  const beforeRecovery = (await snapshot(page)).signals.length;
  await page.getByRole('button', { name: 'Demo controls' }).click();
  await page.getByRole('combobox', { name: 'Sample feed scenario' }).click();
  await page.locator('.ant-select-dropdown:visible').getByText('Normal feed', { exact: true }).click();
  await page.getByRole('button', { name: 'Demo controls' }).click();
  await page.clock.fastForward(4000);
  expect((await snapshot(page)).signals).toHaveLength(beforeRecovery);
  await page.getByRole('button', { name: 'Advance demo candle' }).click();
  for (const theme of ['light', 'dark'] as const) {
    await page.emulateMedia({ colorScheme: theme });
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: `test-results/screenshots/signal-monitor-${theme}.png`, fullPage: true, animations: 'disabled' });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ colorScheme: 'light' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/screenshots/signal-monitor-mobile.png', fullPage: true, animations: 'disabled' });
  expect(errors).toEqual([]);
});
