import { test,expect,type Page } from '@playwright/test';
import { sampleTradingPlan } from '../src/modules/strategies/utils/tradingPlans';
import { strategyChanges } from '../src/modules/strategies/utils/strategyChanges';
import type { SavedStrategy } from '../src/modules/strategies/hooks/useBackendStrategies';
import { reportFixture } from './fixtures/backtestReport';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const revision=(n:number):SavedStrategy=>({...sampleTradingPlan('swing'),name:'Revision example',_id:id,revision:n,savedAt:`2026-09-${String(n).padStart(2,'0')}T04:00:00Z`,risk:{...sampleTradingPlan('swing').risk,riskPercent:n/10,maxPositions:4}});
const sessionId='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const run={...reportFixture(),strategy:revision(2)};
const history=()=>({strategyId:id,currentRevision:10,missingRanges:[],revisions:Array.from({length:10},(_,i)=>({strategy:revision(10-i),source:'saved',inconsistent:false,uses:10-i===2?[{id:run._id,kind:'backtest',at:run.createdAt,status:'completed'},{id:sessionId,kind:'paper',at:'2026-09-20T05:00:00Z',status:'Active'}]:[]}))});
const session={_id:sessionId,strategy:revision(2),active:true,mode:'automatic',ids:['NSE:1'],cashPaise:10000000,initialPaise:10000000,bookedPnlPaise:0};
const paper={sessions:[session],positions:[],orders:[],signals:[{_id:'signal',sessionId,instrumentId:'NSE:1',side:'BUY',barEnd:'2026-09-28T10:00:00Z',referencePrice:100,checks:[]}],observations:[],symbols:{'NSE:1':'ALPHA'},workerRunning:true,marketOpen:false,feed:{state:'waiting',freshIds:[],message:'Market closed'}};
async function setup(page:Page){
 await page.route(url=>url.pathname.startsWith('/api/'),route=>route.fulfill({json:route.request().url().endsWith('/session')?{authenticated:true,mode:'local'}:{}}));
 await page.route('**/api/strategies',route=>route.fulfill({json:[revision(10)]}));
 await page.route(`**/api/strategies/${id}/revisions`,route=>route.fulfill({json:history()}));
 await page.route('**/api/backtests**',route=>{const path=new URL(route.request().url()).pathname;return route.fulfill({json:path.endsWith('/universe')?{stocks:[],listCount:0}:path.endsWith(run._id)?run:[run]});});
 await page.route('**/api/paper',route=>route.fulfill({json:paper}));
 await page.route('**/api/paper/orders?**',route=>route.fulfill({json:{items:[{_id:'order',sessionId,instrumentId:'NSE:1',side:'SELL',status:'filled',quantity:1,source:'signal',createdAt:'2026-09-28T05:00:00Z',fillPaise:11000,entryPaise:10000,realizedPnlPaise:1000}],symbols:paper.symbols,hasMore:false,next:null}}));
}
test('change summary compares rule conditions, limits, targets and disabled sell logic without metadata noise',()=>{
 const before=revision(1),after=revision(2);after.risk.riskPercent=before.risk.riskPercent;
 expect(strategyChanges(before,after)).toEqual([]);
 after.entry.groups[0].conditions[0].rightType='value';after.entry.groups[0].conditions[0].value=987;
 after.risk.maxPositions=8;
 after.risk.exitTargets=[{basis:'risk',value:2,closePercent:40,moveStopTo:0},{basis:'risk',value:5,closePercent:60}];
 after.exit.enabled=false;after.exit.groups=[];
 const changes=strategyChanges(before,after);
 expect(changes).toContainEqual(expect.objectContaining({section:'Buy rules',after:expect.stringContaining('987')}));
 expect(changes).toContainEqual({section:'Risk & execution',label:'Maximum open positions',before:'4',after:'8'});
 expect(changes).toContainEqual(expect.objectContaining({label:'Profit targets · Target 1 · Position to close (%)',after:'40'}));
 expect(changes).toContainEqual(expect.objectContaining({section:'Sell rules',label:'Enabled',after:'Disabled'}));
 expect(before.exit.groups.length).toBeGreaterThan(0);
 const replaced=structuredClone(before);replaced.entry.groups[0].conditions[0].left='rvol';
 const replacedChanges=strategyChanges(before,replaced).filter(c=>c.section==='Buy rules');
 expect(replacedChanges.map(c=>c.label)).toEqual(['Group 1 · condition removed','Group 1 · condition added']);
});
test('ten revisions can be inspected and compared; the exact historical report opens without a write',async({page},info)=>{
 test.setTimeout(60000);
 const errors:string[]=[],writes:string[]=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/')&&r.method()!=='GET')writes.push(r.method());});
 await setup(page);await page.goto('/strategies');await page.getByRole('button',{name:'History',exact:true}).click();
 let drawer=page.getByRole('dialog',{name:'Strategy revision history'});
 await expect(drawer.getByText('10 recorded revisions',{exact:false})).toBeVisible();
 await drawer.getByRole('button',{name:'Revision 2',exact:true}).click();
 await expect(drawer.getByText('Before is revision 1; after is revision 2.')).toBeVisible();
 await drawer.getByLabel('Compare with revision').fill('Revision 10');
 await page.locator('.ant-select-item-option').filter({hasText:'Revision 10'}).click();
 await expect(drawer.getByText('Before is revision 2; after is revision 10.')).toBeVisible();
 await expect(drawer.locator('.strategy-revision-comparison')).toContainText('Risk per trade (%)');
 await expect(drawer.locator('.strategy-revision-comparison')).toContainText('0.2');
 await drawer.getByText('Full saved rules · revision 2',{exact:true}).click();
 await expect(drawer.getByRole('region',{name:'Strategy risk settings'})).toContainText('0.2%');
 await page.screenshot({path:info.outputPath('strategy-history-desktop.png')});
 await page.setViewportSize({width:390,height:844});
 await expect.poll(()=>drawer.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
 await page.screenshot({path:info.outputPath('strategy-history-mobile.png')});
 await page.setViewportSize({width:1440,height:1000});
 await drawer.getByText('Backtests and sessions using revision 2 (2)',{exact:true}).click();
 await drawer.getByRole('link',{name:'Open report'}).click();
 await expect(page).toHaveURL(new RegExp(`run=${run._id}`));
 await expect(page.getByRole('dialog',{name:'Backtest report'}).getByText('This report tested an earlier set of rules')).toBeVisible();
 await page.getByRole('dialog',{name:'Backtest report'}).getByRole('button',{name:'View rules and changes for revision 2'}).click();
 drawer=page.getByRole('dialog',{name:'Strategy revision history'});
 await expect(drawer.getByText('This backtest report uses revision 2')).toBeVisible();
 await expect(drawer.getByText('Before is revision 2; after is revision 10.')).toBeVisible();
 await drawer.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('dialog',{name:'Backtest report'}).getByRole('button',{name:'Close',exact:true}).click();
 await expect(page).not.toHaveURL(new RegExp(`run=${run._id}`));
 await page.getByRole('button',{name:'View report',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'Backtest report'})).toBeVisible();
 expect(writes).toEqual([]);expect(errors).toEqual([]);
});
test('paper accounts, trade history and signals retain their older revision and expose its saved rules',async({page})=>{
 await setup(page);await page.goto(`/paper-trading?session=${sessionId}`);
 await expect(page.getByText('Earlier rules · current 10').first()).toBeVisible();
 await page.getByRole('tab',{name:'Trade & order history'}).click();
 await page.getByRole('button',{name:'View rules and changes for revision 2'}).last().click();
 await expect(page.getByRole('dialog').getByText('This paper trade / order uses revision 2')).toBeVisible();
 await page.goto(`/signal-runner?session=${sessionId}`);
 await expect(page.getByRole('combobox',{name:'Filter signals by strategy'})).toBeVisible();
 await page.getByRole('button',{name:'View rules and changes for revision 2'}).first().click();
 await expect(page.getByRole('dialog').getByText('This signal uses revision 2')).toBeVisible();
});
test('a failed history lookup can retry; unavailable revisions are not presented as invented rules',async({page})=>{
 await setup(page);let attempts=0;
 await page.route(`**/api/strategies/${id}/revisions`,route=>{attempts++;return attempts===1?route.fulfill({status:503,json:{message:'History temporarily unavailable'}}):route.fulfill({json:{...history(),revisions:history().revisions.filter(r=>r.strategy.revision!==5),missingRanges:['5']}});});
 await page.goto('/strategies');await page.getByRole('button',{name:'History',exact:true}).click();
 const drawer=page.getByRole('dialog');await expect(drawer.getByText('Revision history could not be loaded')).toBeVisible();
 await drawer.getByRole('button',{name:'Retry history'}).click();
 await expect(drawer.getByText('Historical snapshots unavailable: revisions 5')).toBeVisible();
 await expect(drawer.getByRole('button',{name:'Revision 5',exact:true})).toHaveCount(0);
});
test('a report uses its exact embedded rules even when a legacy archive shares its revision number',async({page})=>{
 await setup(page);
 const records=history();const archived=records.revisions.find(r=>r.strategy.revision===2)!;archived.strategy.risk.riskPercent=0.9;archived.inconsistent=true;
 await page.route(`**/api/strategies/${id}/revisions`,route=>route.fulfill({json:records}));
 await page.goto(`/strategies?tab=backtests&rule=${id}&run=${run._id}`);
 await page.getByRole('dialog',{name:'Backtest report'}).getByRole('button',{name:'View rules and changes for revision 2'}).click();
 const drawer=page.getByRole('dialog',{name:'Strategy revision history'});
 await expect(drawer.getByText('Different snapshots share this revision number')).toBeVisible();
 await drawer.getByText('Full saved rules · revision 2',{exact:true}).click();
 await expect(drawer.getByRole('region',{name:'Strategy risk settings'})).toContainText('0.2%');
});
test('a report link for another strategy cannot be mistaken for this strategy history',async({page})=>{
 await setup(page);
 await page.route(`**/api/backtests/${run._id}`,route=>route.fulfill({json:{...run,strategy:{...run.strategy,_id:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee'}}}));
 await page.goto(`/strategies?tab=backtests&rule=${id}&run=${run._id}`);
 await expect(page.getByText('This backtest belongs to a different strategy.')).toBeVisible();
 await expect(page.getByRole('dialog',{name:'Backtest report'})).toHaveCount(0);
});
