import { Button, Popover, Select, Switch, Tag, Tooltip } from 'antd';
import { PauseCircleOutlined, PlayCircleOutlined, ReloadOutlined, SettingOutlined, StepForwardOutlined, StopOutlined } from '@ant-design/icons';
import { clockLabel, nextCandle } from '../utils/monitoring';
import type { MonitorDefinition, MonitorWorkspace, StrategyMonitor } from '../types/monitor';

export function MonitorControls({ definitions, selected, monitor, workspace, heldCount, canStart, stale, canSample, onSelect, onStart, onStop, onPause, onCheck, onFeed, onAdvance, onSamples }: {
  definitions: MonitorDefinition[]; selected: MonitorDefinition; monitor?: StrategyMonitor; workspace: MonitorWorkspace; heldCount: number; canStart: boolean; stale: boolean; canSample: boolean;
  onSelect: (id: string) => void; onStart: () => void; onStop: () => void; onPause: () => void; onCheck: () => void;
  onFeed: (feed: MonitorWorkspace['feed']) => void; onAdvance: () => void; onSamples: () => void;
}) {
  const active = !!monitor && monitor.state !== 'stopped';
  const warming = monitor?.state === 'warming';
  const demoControls = <div className="monitor-demo-controls"><h3>Preview monitoring states</h3><label htmlFor="demo-feed">Sample feed</label><Select id="demo-feed" aria-label="Sample feed scenario" value={workspace.feed} onChange={onFeed} options={[{ value: 'healthy', label: 'Normal feed' }, { value: 'delayed', label: 'Delayed data' }, { value: 'disconnected', label: 'Disconnected' }]} /><div className="monitor-demo-holdings"><div><strong>Sample held positions</strong><small>One qualified stock and one outside the list.</small></div><Switch aria-label="Include sample held positions" disabled={!canSample} checked={!!monitor?.samplePositions.length} onChange={onSamples} /></div>{!canSample && <p>Save paired sell rules and publish a monthly list to preview sample holdings.</p>}<p>All prices, candle events and indicator values are synthetic. Advance the demo clock to explore a new candle without waiting.</p></div>;
  return <section className="monitor-panel monitor-control-panel"><div className="monitor-strategy-controls"><div className="monitor-strategy-select"><label htmlFor="monitored-strategy">Strategy · Buy + Sell</label><Select id="monitored-strategy" aria-label="Strategy · Buy + Sell" value={selected.id} onChange={onSelect} showSearch optionFilterProp="label" options={definitions.map(definition => ({ value: definition.id, label: `${definition.name} · Buy + Sell` }))} /></div><div className="monitor-main-actions">{!active || stale ? <Button type="primary" icon={<PlayCircleOutlined aria-hidden />} disabled={!canStart || warming} onClick={onStart}>{stale && active ? 'Update monitor' : 'Start monitoring'}</Button> : <Button type={monitor.entryPaused ? 'primary' : 'default'} icon={monitor.entryPaused ? <PlayCircleOutlined aria-hidden /> : <PauseCircleOutlined aria-hidden />} disabled={warming} onClick={onPause}>{monitor.entryPaused ? 'Resume new entries' : 'Pause new entries'}</Button>}{active && <Tooltip title={heldCount ? 'Held positions need exit checks. Pause new entries instead.' : 'Stop this strategy’s demo monitor'}><span><Button aria-label="Stop monitoring" icon={<StopOutlined aria-hidden />} disabled={heldCount > 0} onClick={onStop} /></span></Tooltip>}<Button icon={<ReloadOutlined aria-hidden />} disabled={warming || !canStart} onClick={onCheck}>Check latest candles</Button></div></div><div className="monitor-demo-strip"><div><Tag color="purple">DEMO SESSION</Tag><span className="monitor-clock">{clockLabel(workspace.clock)} <small>IST</small></span><span className="monitor-demo-date">{new Date(workspace.clock).toLocaleDateString('en-GB', { timeZone: 'Asia/Kolkata', day: '2-digit', month: 'short' })} · runs while this app is open</span></div><div><Button size="small" icon={<StepForwardOutlined aria-hidden />} disabled={monitor?.state !== 'monitoring' || !nextCandle(workspace.clock, selected.entry.cadence)} onClick={onAdvance}>Advance demo candle</Button><Popover trigger="click" placement="bottomRight" content={demoControls}><Button size="small" icon={<SettingOutlined aria-hidden />}>Demo controls</Button></Popover></div></div></section>;
}
