import { Button, Tag } from 'antd';
import { ArrowRightOutlined, ClockCircleOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import { cadenceLabel, clockLabel, nextCandle } from '../utils/monitoring';
import { frameLabels } from '../../qualification/config/metrics';
import type { MonitorDefinition, StrategyMonitor } from '../types/monitor';

export function MonitorTiming({ definition, monitor, clock, onEdit }: { definition: MonitorDefinition; monitor?: StrategyMonitor; clock: number; onEdit: () => void }) {
  const entry = monitor?.definition.entry ?? definition.entry;
  const exit = monitor?.definition.exit ?? definition.exit;
  const frames = [...new Set([entry, ...(exit ? [exit] : [])].flatMap(rule => rule.groups.flatMap(group => group.conditions.flatMap(condition => condition.rightType === 'indicator' ? [condition.leftFrame, condition.rightFrame] : [condition.leftFrame]))))];
  return <aside className="monitor-sidepanels"><section className="monitor-panel monitor-timing"><header><ClockCircleOutlined /><h2>Evaluation timing</h2></header><div className="monitor-timing-row"><span className="monitor-direction buy">BUY</span><div><strong>{cadenceLabel(entry.cadence)}</strong><small>Next close · {clockLabel(nextCandle(clock, entry.cadence))} IST</small></div></div><div className="monitor-timing-row"><span className="monitor-direction sell">SELL</span><div><strong>{exit ? cadenceLabel(exit.cadence) : 'No paired sell rule saved'}</strong><small>{exit ? 'Held positions use their original exit snapshot' : 'Add sell conditions in the rule builder'}</small></div></div><div className="monitor-timeframes"><span>Condition timeframes</span><div>{frames.map(frame => <Tag key={frame}>{frameLabels[frame]}</Tag>)}</div><p>Higher timeframes use completed candles. The current forming candle is excluded.</p><p>Orders would become eligible after confirmation, at the next available price. An exact next-bar opening fill is not guaranteed.</p></div><Button block icon={<ArrowRightOutlined aria-hidden />} onClick={onEdit}>Edit trading rules</Button></section><section className="monitor-panel monitor-exit-policy"><header><SafetyCertificateOutlined /><h2>Position safeguards</h2></header><ul><li>Pausing new entries keeps exit checks running.</li><li>Held stocks stay covered after leaving the monthly list.</li><li>Repeated candle events do not duplicate alerts.</li><li>Stops, targets and session exits use separate checks.</li></ul><p>Feed loss interrupts both entry and exit checks. This preview provides no broker-side protection.</p></section></aside>;
}
