import {z} from 'zod';
export const sourceReportSchema=z.object({title:z.string().max(160),scope:z.string().max(400),tables:z.array(z.object({name:z.string().max(100),columns:z.array(z.string().max(100)).max(20),rows:z.array(z.array(z.union([z.string().max(1000),z.number().finite(),z.null()])).max(20)).max(100)})).max(6)});
export type SourceReport=z.infer<typeof sourceReportSchema>;
function object(value:unknown):Record<string,unknown>{return value&&typeof value==='object'?value as Record<string,unknown>:{};}
function list(value:unknown){return Array.isArray(value)?value.map(object):[];}
function cell(value:unknown):string|number|null{if(value===null||value===undefined)return null;if(value instanceof Date)return value.toISOString();if(typeof value==='number')return Number.isFinite(value)?value:null;if(typeof value==='boolean')return value?'Yes':'No';if(typeof value==='object')return JSON.stringify(value).slice(0,1000);return String(value).slice(0,1000);}
function money(value:unknown){return typeof value==='number'?value/100:null;}
export function sourceReport(tool:string,raw:unknown):SourceReport|undefined{
 const data=object(raw),scope=String(data.scope??'Checked application records').slice(0,400);
 if(tool==='backtests')return {title:'Backtest records',scope,tables:[{name:'Backtest summary',columns:['Report ID','Strategy','Revision','From','Through (exclusive)','Status','Net P&L (INR)','Return (%)','Win rate (%)','Closed trades','Fees (INR)','Data quality','Data gaps'],rows:list(data.runs).map(r=>{const s=object(r.strategy),p=object(r.period),v=object(r.result);return [r.id,s.name,s.revision,p.from,p.to,r.status,v.netPnl,v.returnPercent,v.winRate,v.closedTrades,v.totalFees,object(r.dataQuality).status,Array.isArray(r.qualityIssues)?r.qualityIssues.map(issue=>typeof issue==='string'?issue:JSON.stringify(issue)).join('; '):null].map(cell);})},...list(data.runs).filter(r=>Array.isArray(r.tradeSample)).map(r=>({name:'Latest trade sample',columns:['Report ID','Instrument','Entry time','Exit time','Quantity','Entry (INR)','Exit (INR)','P&L (INR)','Reason'],rows:list(r.tradeSample).map(t=>[r.id,t.instrumentId,t.entryAt,t.exitAt,t.quantity,t.entry,t.exit,t.pnl,t.reason].map(cell))}))]};
 if(tool==='paper')return {title:'Paper trading records',scope,tables:[{name:'Sessions',columns:['Session ID','Strategy','Revision','Active','Mode','Entries paused','Initial capital (INR)','Cash (INR)'],rows:list(data.sessions).map(s=>[s._id,object(s.strategy).name,object(s.strategy).revision,s.active,s.mode,s.entriesPaused,money(s.initialPaise),money(s.cashPaise)].map(cell))},{name:'Recent orders (sample)',columns:['Order ID','Session ID','Instrument','Side','Quantity','Status','Filled at','Fill (INR)','Fees (INR)','Realized P&L (INR)'],rows:list(data.orders).map(o=>[o._id,o.sessionId,o.instrumentId,o.side,o.quantity,o.status,o.filledAt,money(o.fillPaise),money(o.feePaise),money(o.realizedPnlPaise)].map(cell))}]};
 if(tool==='qualification')return {title:'Qualification records',scope,tables:[{name:'Recent scans',columns:['Scan ID','Month','Revision','Status','Evaluated','Qualified','Rejected','Missing inputs','Awaiting history','Cutoff'],rows:list(data.runs).map(r=>[r._id,r.month,r.revision,r.status,r.processed,r.qualified,r.rejected,r.unavailable,r.awaitingHistory,r.cutoff].map(cell))}]};
 return undefined;
}
